### ISSUE TITLE
Collaboration on Parser

### ISSUE THREAD

**Issue by billdenney** [pharmpy/pharmpy#1]
Hi @rikardn,

@MikeKSmith pointed me here (MikeKSmith/rspeaksnonmem#21), and I'd like to collaborate on the parser.  Specifically, I've been wanting a parser-generator for model files that can work from R (in R via reticulate would cover the needs).

As python has the ability to link to antlr4, it may be worth considering the following as a starting point: https://github.com/EightPillars/nmtranprocessorcpp

**Comment by rikardn** [comment]
Thanks @billdenney for reaching out.
 
Pharmpy currently use lark (https://github.com/lark-parser/lark) for parsing. Its main advantage is that it doesn't generate parser code, but creates the parser directly from grammar into an object at run-time. This speeds up development. We can currently parse THETA, OMEGA, SIGMA, DATA, INPUT, general option records and parts of abbreviated code into ASTs, but also into higher level data structures (i.e. SymPy expressions for code records).

For what purpose do you need a parser? Perhaps it is already possible with Pharmpy. If you want to discuss a bit more in depth I would be open for a TC. Please let me know via email in that case.

**Comment by rikardn** [comment]
Pharmpy now has a webpage: https://pharmpy.github.io. The user guide there has some guides for how to work with parameters and random variables in models as a start. Other model manipulations are ongoing work.

I'll close this issue now, but if you have any specific needs or ideas feel free to open new issues.
