### ISSUE TITLE
Upper bound of $THETA set to Inf leads to error message

### ISSUE THREAD

**Issue by SylvieRetout** [pharmpy/pharmpy#100]
I am using a model  originally built with assembler and I want to modify it with pharmpy. However, the upper bound of  $THETA set by default to 'Inf' in assembler leads to an error message in pharmpy. See my example below:

> model <- read_model(model_name)
> print(model)
$PROBLEM
$INPUT ID TIME DV AMT
$DATA data.csv IGNORE=@
$SUBROUTINES ADVAN4  TRANS4 
$MODEL COMP=(DEPOT) COMP=(CENTRAL) COMP=(PERIPHERAL)
$PK
MAT = THETA(1) * EXP(ETA(1))
MDT = THETA(2) * EXP(ETA(2))
VC = THETA(3) * EXP(ETA(3))
VP = THETA(4) * EXP(ETA(4))
Q = THETA(5) * EXP(ETA(5))
CL = THETA(6) * EXP(ETA(6))
ALAG1 = MDT
KA = 1/MAT
S2 = 1/1000
V1 = VC
V2 = VP
$ERROR
CONC = A(2)/VC * S2
Y = CONC + EPS(1) + CONC * EPS(2)
$ESTIMATION METHOD=COND INTERACTION
$THETA (0, 1, Inf) ; POP_MAT
$THETA (0, 1, Inf) ; POP_MDT
$THETA (0, 1, Inf) ; POP_VC
$THETA (0, 1, Inf) ; POP_VP
$THETA (0, 1, Inf) ; POP_Q
$THETA (0, 1, Inf) ; POP_CL
$OMEGA 0.1; IIV_MAT
$OMEGA 0.1; IIV_MDT
$OMEGA 0.1; IIV_VC
$OMEGA 0.1; IIV_VP
$OMEGA 0.1; IIV_Q
$OMEGA 0.1; IIV_CL
$SIGMA 0.1; RUV_ADD
$SIGMA 0.1; RUV_PROP

> model$parameters
Error in py_get_attr_impl(x, name, silent) : 
  UnexpectedCharacters: No terminal defined for 'I' at line 1 col 9

 (0, 1, Inf) ; POP_MAT
        ^

Expecting: {'FIX', 'NUMERIC', 'POS_INF', 'WS', 'RPAR'}

**Comment by rikardn** [comment]
Thanks for reporting this. This was due to the parser only recognizing `INF` in all upper case. This has been fixed with 9ac80fadc55f7f6294bd8347db6124989afdd41f in version 0.15.0 (released yesterday).
