### ISSUE TITLE
resmod model description is different from other modules

### ISSUE THREAD

**Issue by liuxl17** [pharmpy/pharmpy#1003]
In the final result.csv file, the summary_tool of resmod also contains the model description of iivsearch (in this case is [MAT]+[VC,MDT,QP1]). While the results of other subtools only have a description of their own. 
Also, the base model used in resmod was mistakenly summarized into the final output, the row where the ranking column is blank. I suppose this row needs to be removed.
![image](https://user-images.githubusercontent.com/53524647/181286677-c88fe8cc-5240-4654-b296-84ad11598380.png)

**Comment by stellabelin** [comment]
Hi! Thank you for reporting, I agree that the description should be relevant to the subtool used and cleared between subtools! This can be changed when we always copy the start model

**Comment by stellabelin** [comment]
Relevant issue here: #1054. Closing this issue.
