### ISSUE TITLE
Multiple covariate effects on one PK parameter

### ISSUE THREAD

**Issue by SylvieRetout** [pharmpy/pharmpy#101]
I would like to plug both a body weight effect and a race effect on CL/F, such that: CL/F= CL/F_pop * (BWT/BWT_median)^THETA(7) * (1 + THETA(8) *RACE) with RACE coded 0/1
However, the system does not take it into account properly, creating one line of CL/F expression per covariate. See my example below:

 user_effect = '(1 + theta * cov)'
 
model <- model %>%
  add_covariate_effect("CL", "WT", "(cov/median)**theta") %>%
  add_covariate_effect("CL", "RACE", user_effect, operation='*') %>%
  update_source()

C:\PROGRA~1\Python38\lib\site-packages\pharmpy\modeling\covariate_effect.py:67: UserWarning: Covariate effect already exists
  warnings.warn('Covariate effect already exists')
> model

```
$PROBLEM
$INPUT  ID TIME DV AMT WT GEND AGE RACE STUD
$DATA data2.csv IGNORE=@
$SUBROUTINES ADVAN4  TRANS4 
$MODEL COMP=(DEPOT) COMP=(CENTRAL) COMP=(PERIPHERAL)
$PK
MAT = THETA(1) * EXP(ETA(1))
MDT = THETA(2) * EXP(ETA(2))
VC = THETA(3) * EXP(ETA(3))
VP = THETA(4) * EXP(ETA(4))
Q = THETA(5) * EXP(ETA(5))
CL = THETA(6) * EXP(ETA(6))
WT_MEDIAN = 66.3000
CLWT = (WT/WT_MEDIAN)**THETA(7)
CL = CL*CLWT
CLRACE = RACE*THETA(8) + 1
CL = CL*CLRACE
ALAG1 = MDT
KA = 1/MAT
V1 = VC
V2 = VP
```

**Comment by stellabelin** [comment]
Thank you for reporting this! This issue has now been addressed so that the effect will look like this instead:
```
CL = CL*CLRACE*CLWT
```
This will be available in the next release. I could however not reproduce the user warning in this issue, where there any step previously?

**Comment by rikardn** [comment]
I think this has been resolved. Please reopen or open a new issue if problems remain.
