### ISSUE TITLE
Duplication of median covariate value assignment in NM code in case the covariate impacts more than one parameter

### ISSUE THREAD

**Issue by SylvieRetout** [pharmpy/pharmpy#102]
If a same covariate impacts two different PK parameters, with a function taking into account its median value, then the line imputing the cov_median to its value in the dataset is written twice in the model, which is not necessary. See the example below with line "WT_MEDIAN = 66.3000" written twice:

model <- model %>%
  add_covariate_effect("CL", "WT", "(cov/median)**theta") %>%
  add_covariate_effect("CL", "RACE", user_effect, operation='*') %>%
  add_covariate_effect("VP", "WT", "(cov/median)**theta") %>%
    update_source()

$PK
MAT = THETA(1) * EXP(ETA(1))
MDT = THETA(2) * EXP(ETA(2))
VC = THETA(3) * EXP(ETA(3))
VP = THETA(4) * EXP(ETA(4))
WT_MEDIAN = 66.3000
VPWT = (WT/WT_MEDIAN)**THETA(9)
VP = VP*VPWT
Q = THETA(5) * EXP(ETA(5))
CL = THETA(6) * EXP(ETA(6))
WT_MEDIAN = 66.3000
CLWT = (WT/WT_MEDIAN)**THETA(7)
CL = CL*CLWT
CLRACE = RACE*THETA(8) + 1
CL = CL*CLRACE
ALAG1 = MDT

**Comment by rikardn** [comment]
Thanks for reporting this.
