### ISSUE TITLE
Initial values setting moving from a 2 compartment to a 3 compartment model in modelsearch

### ISSUE THREAD

**Issue by SylvieRetout** [pharmpy/pharmpy#1020]
Hi,

Using modelsearch and moving from a 2 compartment to a 3 compartment model, I noticed that the initial parameter values for the 3 compartment model where initialized as followed:
Pop_QP1 = Pop_QP1_2cpt / 10
Pop_QP2 = Pop_QP1_2cpt
pop_VP1 = Pop_VP1_2cpt
pop_VP2 = Pop_VP1_2cpt

This is not aligned with the documentation which states: 
Pop_QP1 = Pop_QP1_2cpt / 2
Pop_QP2 = Pop_QP1_2cpt /2
pop_VP1 = Pop_VP1_2cpt
pop_VP2 = Pop_VP1_2cpt

Could you please correct that?
In addition,  I noticed that moving from a 1 compartment model to a 2 compartment model, the peripheral volume is set to the central volume scaled by a factor 0.05, as mentioned in the documentation. What is the rational for using such a lower value? This is not the scaling factor I would have applied in a manual model building process.

Thanks,
Kind regards,

Sylvie

**Comment by stellabelin** [comment]
Hi! Thank you for reporting! The documentation has been corrected in 2905f5ed8a69ab860ebd58ae0c3091af2b807c6e. The rational for 0.05 will be explained at the next meeting by Mats, but we should perhaps have the explanations for all initial estimates documented. The value you posted in your second comment is 90% of QP1, so when going from a 2C model to a 3C, QP1 will have 10% of its estimated value and QP2 90%.

**Comment by stellabelin** [comment]
I've created a new issue #1034 to add more documentation about rational behind choosing these initial estimates, will close this issue since the documentation has been corrected.
