### ISSUE TITLE
Adding IOV is partially deleting the OMEGA block

### ISSUE THREAD

**Issue by SimonBuatois** [pharmpy/pharmpy#103]
Hi,

Using the Pheno example I tried to add some IOV using the following R command line:

# a: Reading in a NONMEM model and printing its structure (run line by line to see the output)
model <- read_model(model_name)
print(model)

![image](https://user-images.githubusercontent.com/75624013/107010675-f0f0cb80-6796-11eb-8512-23b188bcfdd3.png)

# b: Adding IOV on ETA(1)
model <- model %>%
  add_iov("DOSE",list('ETA(1)')) %>%
  update_source()

Which gives me the following output:
![image](https://user-images.githubusercontent.com/75624013/107010506-b5ee9800-6796-11eb-8fcb-bb2a950662a4.png)

As you can see, the Omega block now only contains the initial estimate for IOV.

**Comment by stellabelin** [comment]
Hi, thanks for reporting. When I tried to recreate this issue I got the same bug when I set all values in "DOSE" to the same value. In the data for this example, do all rows have the same value for "DOSE"?

**Comment by SimonBuatois** [comment]
Hi Stella, You are right, My dose had always the same value.
We should perhaps add in error message in such a case?

**Comment by stellabelin** [comment]
I agree, that would be useful. I will implement it for the next release!
