### ISSUE TITLE
Verify input to all AMD tools

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#1032]
Such as rank function, algorithm etc. This should be done when starting the tool, if e.g. `rank_type` is misspecified `run_modelsearch` will not crash until post-processing.

**Comment by pharmpy-dev-123** [comment]
I think it would also make sense for `run_amd` to pre-check what it can for the used subtools. So that it stops right at the start of `run_amd` if needed.

**Comment by stellabelin** [comment]
I agree! Would it make sense that each subtool have a function `verify_input` which AMD can loop through? And then each `create_workflow` can also use their respective verify-function?

**Comment by pharmpy-dev-123** [comment]
Yep! I'll see how we can avoid too much duplication.

**Comment by pharmpy-dev-123** [comment]
Waiting for #984 to be merged.
