### ISSUE TITLE
Duplication of median covariate value assignement in NM code in case of multiple impacts of one cov

### ISSUE THREAD

**Issue by SimonBuatois** [pharmpy/pharmpy#104]
If a same covariate impacts two different PK parameters, with a function taking into account its median value, then the line imputing the cov_median to its value in the dataset is written twice in the model. See the example below:

model <- model %>%
  add_covariate_effect("CL", "WT", "(cov/median)**theta") %>%
  add_covariate_effect("CL", "RACE", user_effect, operation='*') %>%
  add_covariate_effect("VP", "WT", "(cov/median)**theta") %>%
    update_source()

$PK
MAT = THETA(1) * EXP(ETA(1))
MDT = THETA(2) * EXP(ETA(2))
VC = THETA(3) * EXP(ETA(3))
VP = THETA(4) * EXP(ETA(4))
WT_MEDIAN = 66.3000
VPWT = (WT/WT_MEDIAN)**THETA(9)
VP = VP*VPWT
Q = THETA(5) * EXP(ETA(5))
CL = THETA(6) * EXP(ETA(6))
WT_MEDIAN = 66.3000
CLWT = (WT/WT_MEDIAN)**THETA(7)
CL = CL*CLWT
CLRACE = RACE*THETA(8) + 1
CL = CL*CLRACE
ALAG1 = MDT

**Comment by stellabelin** [comment]
Thanks for reporting! This was addressed in issue #102 and has since been solved (4f20234f604bbbd4c46835692d2c545b53c30b60), so in the next release there should be no duplicated lines!
