### ISSUE TITLE
Bug in the display of ODE when adding a peripheral compartment 

### ISSUE THREAD

**Issue by SimonBuatois** [pharmpy/pharmpy#105]
Using the pheno example I tried to add a pheripheral compartment using the following R command line:

model %>%
+   add_peripheral_compartment() %>%
+   update_source()

The model code is correct, however, in the ode system the following figure is displayed:

![image](https://user-images.githubusercontent.com/75624013/107014760-55625980-679c-11eb-99e0-25ffdc2c0bf2.png)

As you can see, the inter-compartment clearance as a different name depending if it is going from the central to the peripheral compartment (QP1) of from the peripheral to the central (Q).
Even thought, it is mention in the $PK that Q=QP1 I would suggest to use the same names for both arrows.

Kind regards,
Simon

**Comment by rikardn** [comment]
I agree. This is a bug.
