### ISSUE TITLE
Error message with the Fix_parameters function

### ISSUE THREAD

**Issue by SylvieRetout** [pharmpy/pharmpy#106]
I tested the following code to fix the Theta(1) value:
model <- model %>%
+   fix_parameters(c('THETA(1)')) %>% 
+   update_source()

I got the error message below:
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  KeyError: 'Parameter "THETA(1)" does not exist' 

This issue can be solved if we used 'POP_MAT' instead of 'THETA(1)' as an argument of the function. This is however not aligned with the guidance.
In addition, it could be useful to get an option in that fix_parameters function to allow the user to fix the parameter to a given value the user would specify: eg fix_parameters(c('THETA(1)'), val=c(1.4)) 

My current model is:
$PROBLEM
$INPUT  ID TIME DV AMT WT GEND AGE RACE STUD
$DATA data2.csv IGNORE=@
$SUBROUTINES ADVAN4  TRANS4 
$MODEL COMP=(DEPOT) COMP=(CENTRAL) COMP=(PERIPHERAL)
$PK
MAT = THETA(1) * EXP(ETA(1))
MDT = THETA(2) * EXP(ETA(2))
VC = THETA(3) * EXP(ETA(3))
VP = THETA(4) * EXP(ETA(4))
WT_MEDIAN = 66.3000
VPWT = (WT/WT_MEDIAN)**THETA(11)
VP = VP*VPWT
Q = THETA(5) * EXP(ETA(5))
CL = THETA(6) * EXP(ETA(6))
WT_MEDIAN = 66.3000
CLWT = (WT/WT_MEDIAN)**THETA(7)
CL = CL*CLWT
IF (RACE.EQ.0.0) THEN
CLRACE = 1
ELSE IF (RACE.EQ.3.0) THEN
CLRACE = THETA(8) + 1
ELSE IF (RACE.EQ.2.0) THEN
CLRACE = THETA(9) + 1
ELSE IF (RACE.EQ.1.0) THEN
CLRACE = THETA(10) + 1
END IF
CL = CL*CLRACE
ALAG1 = MDT
KA = 1/MAT
V1 = VC
V2 = VP
$ERROR
CONC = A(2)/VC * 1000
Y = CONC + EPS(1) + CONC * EPS(2)
$ESTIMATION METHOD=COND INTERACTION
$THETA (0, 1) ; POP_MAT
$THETA (0, 1) ; POP_MDT
$THETA (0, 1) ; POP_VC
$THETA (0, 1) ; POP_VP
$THETA (0, 1) ; POP_Q
$THETA (0, 1) ; POP_CL
$THETA  (-100000,0.001,100000) ; POP_CLWT
$THETA  (-100000,0.001,100000) ; POP_CLRACE_1
$THETA  (-100000,0.001,100000) ; POP_CLRACE_2
$THETA  (-100000,0.001,100000) ; POP_CLRACE_3
$THETA  (-100000,0.001,100000) ; POP_VPWT
$OMEGA 0.1; IIV_MAT
$OMEGA 0.1; IIV_MDT
$OMEGA 0.1; IIV_VC
$OMEGA 0.1; IIV_VP
$OMEGA 0.1; IIV_Q
$OMEGA 0.1; IIV_CL
$SIGMA 0.1; RUV_ADD
$SIGMA 0.1; RUV_PROP

**Comment by stellabelin** [comment]
Hi! Thank you for the issue! The reason that 'POP_MAT' instead of 'THETA(1)'  is used is that it expects the Pharmpy name (if 'POP_MAT' is created in a transformation in Pharmpy, is this the case here?), but I agree that it's a little unclear, the user guide will be updated to reflect this! Being able to fix a parameter to a specific value would indeed be a useful feature and it should be implemented shortly!

**Comment by SylvieRetout** [comment]
Hi,
Thanks for your answers. FYI, I am using a model that was originally created with assemblerr. 
Sylvie

**Comment by stellabelin** [comment]
There are now functions to fix and unfix parameters to a specified value or a list of values (bdfc2025de3648f458fae19fb7f7777ab103b56e). The documentation has been updated and a new page for using Pharmpy with NONMEM models have been written (4ee88468315ecd1d1d5640745fc9ccebca985e38) where the naming is described in more detail. Both of these will be in the next release.

**Comment by SylvieRetout** [comment]
Good, thank you!
Kind regards,

Sylvie


-----------------------------------

Sylvie Retout, PhD


Senior Principal Scientist, Clinical Pharmacometrics

Roche Pharma Research & Early Development
Roche Innovation Center Basel

Institut Roche

4, cours de l’Ile Seguin

92100 Boulogne-Billancourt

Phone: +33 1 47 61 40 36

Mobile: +33 6 73 99 50 65

mailto: sylvie.retout@roche.com

This message and any of the attachments may contain confidential and
proprietary material for the sole use of the intended recipient. Any review
of distribution by others is strictly prohibited. If you are not the
intended recipient please contact the sender and delete all copies.
