### ISSUE TITLE
Copy tmp run directory if tool crashes

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#1082]
E.g. if a tool fails due to timeout or a raised error, Pharmpy should copy the NONMEM directory from tmp so that it doesn't get deleted. Check if Dask already has system for this

**Comment by rikardn** [comment]
Let us solve this first for situations where NONMEM crashed or the crash originated in the NONMEM run function. This is an easier problem to solve.

**Comment by ZheHuang96** [comment]
- [ ] When the crash is on NONMEM side, copy all the files of failed NONMEM model from tmp directory. (Currently, we define 'failed ' means no .ext, .lst files generated in NONMEM run. )
- [ ] When the crash is due to Pharmpy errors, ...

**Comment by ZheHuang96** [comment]
Hi @pharmpy-dev-123 , 

#1232 is to solve the first target, when the cash is on nonmem side, copy all files from tmp directory. I saw there are some conflicts in it, I am going to resolve them. I think it would be great to test the functionality but I haven't found any examples yet. So I set it as a draft, if we don't need to add tests, I think we can review it after resolving the conflicts.

The second target is about the crash in Pharmpy, like timeout and so on. I am not sure how to solve it.

**Comment by pharmpy-dev-123** [comment]
OK.

**Comment by stellabelin** [comment]
If NONMEM fails we already copy everything. If Pharmpy fails the result files from NONMEM should be unaffected since this happens outside of the estimation. If a timeout occurs on e.g. a cluster it would be hard to capture the error, and with the `resume`-option this type of error would not be as serious. Closing this issue.
