### ISSUE TITLE
Error with the AMD tool: Simple IV drug, reduced search space

### ISSUE THREAD

**Issue by SimonBuatois** [pharmpy/pharmpy#1088]
Hi

I tried to run the AMD tool and faced an issue:

Example:
-simple IV drug
-search space = only peripheral 1
-no covariates
-no IOV

R code:

#run Automatic Model Development (AMD) tool
res <- run_amd(
    dataset_path,
    modeltype='pk_iv',
    search_space='PERIPHERALS(1)')

output:
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'NoneType' object has no attribute 'best_model' 

FYI, it seems that all subtools worked since I can find the outputs of the different IIV, structural, res models directly in the WD.

KR,
Simon

**Comment by pharmpy-dev-123** [comment]
#1065 was merged into `main`. Should be included in release `0.76.1` or `0.77.0`.

**Comment by pharmpy-dev-123** [comment]
Fixed in release `0.76.5`. Closing.
