### ISSUE TITLE
Optimize parsing of NONMEM models

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#1134]
According to @pharmpy-dev-123 40% of unit test time is spent in parsing NONMEM models. This finding also reflects the general feeling that this parsing is slow. We can use this issue to discuss solutions.

**Comment by rikardn** [comment]
Some ideas:

1. Move grammars to LALR(1). This can be very time consuming since there are many things in the grammars that need changing and the use of the parse trees in the code also would most probably need changing

2. Move to hand rolled parsers for the simplest records. For example $INPUT and the option records should be easy to parse using hand rolled parsers.

3. Using other parser generator. The benefit of using lark is that it is easy to use, at lest the earley parser. We should use this option only if other options fail.

**Comment by rikardn** [comment]
NONMEM results parsing could also affect this

**Comment by pharmpy-dev-123** [comment]
Once #1029 gets merged NONMEM parsing will take 58% of unit test time.

**Comment by pharmpy-dev-123** [comment]
#1304 is merged. Done!
