### ISSUE TITLE
Results of the covariate tool use the wrong `rank_type`

### ISSUE THREAD

**Issue by SimonBuatois** [pharmpy/pharmpy#1172]
Please find below a few comments to be considered for the covariate tool:

Results.csv file: not easy to understand:
=> Reports BIC but SCM is based on LRT tests…
=> Not sure what is the best model from the forward step, and then from the backward step, could be good to highlight the final forward and backward models.

![image](https://user-images.githubusercontent.com/75624013/191030479-b72cbbfc-1283-44f5-b7d5-8d20da801360.png)

**Comment by pharmpy-dev-123** [comment]
> => Reports BIC but SCM is based on LRT tests…

This has been fixed by #1175. Will be available in the next release (`0.78.1` or `0.79.0`).

> => Not sure what is the best model from the forward step, and then from the backward step, could be good to highlight the final forward and backward models.

This will be addressed by other fixing new issues, see

  - #1236
  - #1237

I am closing this issue for clarity.
