### ISSUE TITLE
Unparseable model code generated by `add_covariate_effect`

### ISSUE THREAD

**Issue by SimonBuatois** [pharmpy/pharmpy#1174]
Test the cov tool.
Issue with categorical covariates:

Coding error with respect to Study effect on CL
THETA0 parameter undefined
It may be due to the coding of STUD (numerical values corresponding to the study numbers) ??
No issue with RACE, coded as 1, 2, 3, 9

See the image below:

![image](https://user-images.githubusercontent.com/75624013/191029969-a99a27a7-28ca-41bd-a4d1-a91aeb911c85.png)

**Comment by pharmpy-dev-123** [comment]
This is a bug that stems from the first category not being the most common, among other things. We have a fix ready in #1004. I hope we can get it landed in the next release.

**Comment by pharmpy-dev-123** [comment]
Will be included in the next release (`v0.78.1` or `v0.79.0`).
