### ISSUE TITLE
Adding covariate effect creates illegal code

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#118]
Using the phenobarbital model I did

```
pharmpy model add_cov_effect pheno_real.mod W WGT exp -o run1.mod
```

The following `$ERROR` was generated:

```
$ERROR

      Y=F+W*EPS(1)

WGT_MEDIAN = 1.30000
WWGT = EXP(THETA(4)*(WGT - WGT_MEDIAN))
W = F*WWGT
      IPRED=F         ;  INDIVIDUAL-SPECIFIC PREDICTION
      IRES=DV-IPRED   ;  INDIVIDUAL-SPECIFIC RESIDUAL
      IWRES=IRES/W    ;  INDIVIDUAL-SPECIFIC WEIGHTED RESIDUAL
```

The `W` is needed in the expression for `Y` but is not defined until later. Is this always a problem or is it because the parameter is in `$ERROR` ?

**Comment by stellabelin** [comment]
I can reproduce it, doesn't seem to be due to the fact that it is in `$ERROR` but a bug in how it finds the relevant assignment.
