### ISSUE TITLE
strange error message when reading a model created in Assemblerr

### ISSUE THREAD

**Issue by SylvieRetout** [pharmpy/pharmpy#122]
I read the following model, created from assemblerr:
 model <- read_model(model_name)
> print(model)
$PROBLEM
$INPUT ID TIME DV AMT
$DATA data.csv IGNORE=@
$SUBROUTINES ADVAN13 TOL=6
$MODEL COMP=(DOSE) COMP=(CENTRAL) COMP=(PERIPH) COMP=(LIVER)
$PK
MAT = THETA(1) * EXP(ETA(1))
CL = THETA(2) * EXP(ETA(2))
VC = THETA(3) * EXP(ETA(3))
Q = THETA(4) * EXP(ETA(4))
VP = THETA(5) * EXP(ETA(5))
VM = THETA(6) * EXP(ETA(6))
KM = THETA(7) * EXP(ETA(7))
KLO = THETA(8) * EXP(ETA(8))
VL = THETA(9) * EXP(ETA(9))
KA = 1/MAT
$DES
DADT(1) = -(KA * A(1))
DADT(2) = KA * A(1) + Q/VP * A(3) - (Q/VC * A(2) + A(2)/VC * VM/(KM + A(2)/VC))
DADT(3) = Q/VC * A(2) - Q/VP * A(3)
DADT(4) = A(2)/VC * VM/(KM + A(2)/VC) - KLO * A(4)
$ERROR
CONC = A(2)/VC
Y = CONC + EPS(1)
$ESTIMATION METHOD=COND INTER
$COVARIANCE PRINT=E
$THETA (0, 1, Inf) ; POP_MAT
$THETA (0, 1, Inf) ; POP_CL
$THETA (0, 1, Inf) ; POP_VC
$THETA (0, 1, Inf) ; POP_Q
$THETA (0, 1, Inf) ; POP_VP
$THETA (0, 1, Inf) ; POP_VM
$THETA (0, 1, Inf) ; POP_KM
$THETA (0, 1, Inf) ; POP_KLO
$THETA (0, 1, Inf) ; POP_VL
$OMEGA 0.1; IIV_MAT
$OMEGA 0.1; IIV_CL
$OMEGA 0.1; IIV_VC
$OMEGA 0.1; IIV_Q
$OMEGA 0.1; IIV_VP
$OMEGA 0.1; IIV_VM
$OMEGA 0.1; IIV_KM
$OMEGA 0.1; IIV_KLO
$OMEGA 0.1; IIV_VL
$SIGMA 0.1; RUV_ADD

When asking for the parameters, I got the following error message:
> model$parameters
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: 'str' object has no attribute 'name'

Same with :
> model$statements$ode_system
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: 'str' object has no attribute 'name'

But not with:
> model$random_variables
ETA(1)~ 𝒩 (0, IIV_MAT)
ETA(2)~ 𝒩 (0, IIV_CL)
ETA(3)~ 𝒩 (0, IIV_VC)
ETA(4)~ 𝒩 (0, IIV_Q)
ETA(5)~ 𝒩 (0, IIV_VP)
ETA(6)~ 𝒩 (0, IIV_VM)
ETA(7)~ 𝒩 (0, IIV_KM)
ETA(8)~ 𝒩 (0, IIV_KLO)
ETA(9)~ 𝒩 (0, IIV_VL)
EPS(1)~ 𝒩 (0, RUV_ADD)

Could you please let me know what it means?
Thank you,

Sylvie

**Comment by rikardn** [comment]
Thanks for reporting this. I can confirm that it is a bug.
