### ISSUE TITLE
error in updating transit compartment model from n to n+1 transit or from n to n-1 transit

### ISSUE THREAD

**Issue by cossonvalerie** [pharmpy/pharmpy#123]
moving from a 1st order model too a transit absorption model works well the rate constants are correctly set according to the number of transit
set_transit_compartments(model,3) %>%
  update_source()
$PK
MDT = THETA(6)
MAT = THETA(1) * EXP(ETA(1))
CL = THETA(2)*EXP(ETA(2))
VC = THETA(3)*EXP(ETA(3))
Q = THETA(4)*EXP(ETA(4))
VP = THETA(5)*EXP(ETA(5))
KA = 1/MAT
V2 = VC
V3 = VP
K12 = 3/MDT
K23 = 3/MDT
K34 = 3/MDT
K45 = KA
K56 = Q/V2
K50 = CL/V2
K65 = Q/V3

When increasing or decreasing the number of transit, the rate constants are no longer adequately set according to the number of transit
From 3 to 4 transit
$PK
(...)
KA = 1/MAT
V2 = VC
V3 = VP
K23 = 3/MDT
K34 = 3/MDT
K45 = 3/MDT
K56 = KA
K67 = Q/V2
K60 = CL/V2
K76 = Q/V3
K12 = K23

K12, K23, K34 and K45 should equal 4/MDT

From 3 to 2 transit
$PK
(...)
KA = 1/MAT
V2 = VC
V3 = VP
K12 = 3/MDT
K23 = 3/MDT
K34 = KA
K45 = Q/V2
K40 = CL/V2
K54 = Q/V3

K12 and K23 should equal 2/MDT

**Comment by rikardn** [comment]
Thanks for reporting this. I can confirm that it is a bug.
