### ISSUE TITLE
Cannot read Json file of a bootstrap

### ISSUE THREAD

**Issue by cossonvalerie** [pharmpy/pharmpy#136]
I have been able to create the Json file of a boostrap, but when I want to read it using the following command:
read_results("results.json")

I get the following error message

 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  JSONDecodeError: Expecting value: line 1 column 1 (char 0) 

PS: Json file in question provided in Box

**Comment by rikardn** [comment]
Thanks for reporting this. I'll have a look at your `results.json`

**Comment by rikardn** [comment]
I think I'll also need the bootstrap directory for which this was created. Could you please upload that to Box as well?

**Comment by rikardn** [comment]
The file provided is not a json file. It is csv. How was it created?

**Comment by cossonvalerie** [comment]
Dear Rikard,

I think you found out the problem, when I thought I created the Json file,
I did not use the correct function.

I have redone the test with the following function

res$to_json("results.json")

and I can now read the file with

read_results("results.json")

Sorry for my mistake.

Kind regards

Valerie

Valerie Cosson, PhD
DTA Clinical Pharmacometrics Head I2O

Pharmaceutical Sciences
Roche Pharma Research and Early Development

Roche Innovation Center Basel



F. Hoffmann-La Roche Ltd
Grenzacherstrasse 124

4070 Basel

Switzerland

Phone +41 61 687 51 12

mailto: ***@***.***

**Comment by rikardn** [comment]
That is great! I'll close this then.

**Comment by cossonvalerie** [comment]
Yes you can. Just a note,  I realize how it happens, I run both commands in
a row

res$to_json("results.json") # to save the results as a JSON file
res$to_csv("results.json") # to save the results as a CSV file

As the files that are created have the same name, and both appear in the
Type column of explorer as JSON file, I did not realize that it was the csv
file that we were trying to read.

So my question to you, should the name of the files that are created be
different to differentiate between the Json file and the CSV file?

Kind regards

Valerie

Valerie Cosson, PhD
DTA Clinical Pharmacometrics Head I2O

Pharmaceutical Sciences
Roche Pharma Research and Early Development

Roche Innovation Center Basel



F. Hoffmann-La Roche Ltd
Grenzacherstrasse 124

4070 Basel

Switzerland

Phone +41 61 687 51 12

mailto: ***@***.***
