### ISSUE TITLE
Rename symbols with spaces in statements

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#1362]
### Bug report

When reading in a model with spaces in the parameter name (e.g. `THETA (1)`), the name is not translated correctly in the statements. The following code: 

```
$PROBLEM base model
$INPUT ID DV TIME
$DATA file.csv IGNORE=@

$PRED
Y = THETA(1) + ETA(1) + EPS(1)

$THETA 1  ; TH1
$OMEGA 2 ; OM1
$SIGMA 3 ; SI1
$ESTIMATION METHOD=1 INTER
```

Gives this Pharmpy statement (i.e. theta is replaced with Pharmpy name): `Y = EPS(1) + ETA(1) + TH₁`

While the following code: 

```
$PROBLEM base model
$INPUT ID DV TIME
$DATA file.csv IGNORE=@

$PRED
Y = THETA (1) + ETA(1) + EPS(1)

$THETA 1  ; TH1
$OMEGA 2 ; OM1
$SIGMA 3 ; SI1
$ESTIMATION METHOD=1 INTER
```

Gives the following statement: `Y = EPS(1) + ETA(1) + THETA (1)`

**Comment by pharmpy-dev-123** [comment]
@stellabelin Thanks! I am writing a fix.
