### ISSUE TITLE
COVsearch in run_amd

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmpy#1377]
### Bug report

Hi. After running the amd tool with an example (dataset7_27NOV2022):
```
res <- run_amd(
    dataset_path,
    modeltype='pk_oral',
    # search_space='PERIPHERALS(1)',
    # order=c('structural', 'iivsearch', 'residual', 'iovsearch', 'allometry', 'covariates'),
    search_space = "LET(CATEGORICAL,[SEX,DOSE]);LET(CONTINUOUS,[AGE,BWT])",
    cl_init= CL,
    vc_init= V,
    mat_init= MAT,
    # occasion='VISI'
    )
```

According to results.csv of the amd tool, model covsearch_run10 has been selected:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/abrantj1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/abrantj1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

summary_tool |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
tool | selected_model | description | ofv | dofv | n_params | d_params
start | start | Start model | 6104.209966 | 0 | 8 | 0
modelsearch | modelsearch_run94 | PERIPHERALS(1);ELIMINATION(MM);ABSORPTION(SEQ-ZO-FO) | 2386.376662 | 3717.833304 | 13 | 5
iivsearch | iivsearch_run34 | [VC,KM,QP1,VP1] | 2261.953959 | 124.4227027 | 18 | 5
ruvsearch | best_ruvsearch_1 | time_varying3 | 2199.740978 | 62.21298075 | 19 | 1
covsearch | covsearch_run10 | (VC-BWT-exp) | 2168.905472 | 30.83550677 | 20 | 1

</body>

</html>

However, even though this model is the best in the first forward step of COVsearch (lowest OFV), it does not seem to be selected for a 2nd forward step. Is this the intended behavior? 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/abrantj1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/abrantj1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

step | model | description | pvalue | goal_pvalue | is_backward | selected | n_params | d_params | dofv | ofv | parent_model
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | best_ruvsearch_1 | time_varying3 |   |   | FALSE | TRUE | 19 | 0 | 0 | 2199.740978 | best_ruvsearch_1
1 | covsearch_run1 | (KM-AGE-exp) | 0.001784054 | 0.05 | FALSE | FALSE | 20 | 1 | 9.759427809 | 2189.98155 | best_ruvsearch_1
1 | covsearch_run2 | (KM-BWT-exp) | 0.365592965 | 0.05 | FALSE | FALSE | 20 | 1 |   |   | best_ruvsearch_1
1 | covsearch_run3 | (KM-DOSE-cat) | 0.002475967 | 0.05 | FALSE | FALSE | 21 | 2 | 12.00224865 | 2187.73873 | best_ruvsearch_1
1 | covsearch_run4 | (KM-SEX-cat) | 0.072279376 | 0.05 | FALSE | FALSE | 20 | 1 |   |   | best_ruvsearch_1
1 | covsearch_run5 | (QP1-AGE-exp) | 0.025291536 | 0.05 | FALSE | FALSE | 20 | 1 | 5.003813331 | 2194.737165 | best_ruvsearch_1
1 | covsearch_run6 | (QP1-BWT-exp) | 0.931720589 | 0.05 | FALSE | FALSE | 20 | 1 |   |   | best_ruvsearch_1
1 | covsearch_run7 | (QP1-DOSE-cat) | 0.051279712 | 0.05 | FALSE | FALSE | 21 | 2 |   |   | best_ruvsearch_1
1 | covsearch_run8 | (QP1-SEX-cat) | 0.099175744 | 0.05 | FALSE | FALSE | 20 | 1 |   |   | best_ruvsearch_1
1 | covsearch_run9 | (VC-AGE-exp) | 0.04433937 | 0.05 | FALSE | FALSE | 20 | 1 | 4.043591308 | 2195.697387 | best_ruvsearch_1
1 | covsearch_run10 | (VC-BWT-exp) | 2.81E-08 | 0.05 | FALSE | FALSE | 20 | 1 | 30.83550677 | 2168.905472 | best_ruvsearch_1
1 | covsearch_run11 | (VC-DOSE-cat) | 0.037504581 | 0.05 | FALSE | FALSE | 21 | 2 | 6.566584377 | 2193.174394 | best_ruvsearch_1
1 | covsearch_run12 | (VC-SEX-cat) | 0.047159756 | 0.05 | FALSE | FALSE | 20 | 1 | 3.939679713 | 2195.801299 | best_ruvsearch_1
1 | covsearch_run13 | (VP1-AGE-exp) | 0.330033124 | 0.05 | FALSE | FALSE | 20 | 1 |   |   | best_ruvsearch_1
1 | covsearch_run14 | (VP1-BWT-exp) | 0.380582395 | 0.05 | FALSE | FALSE | 20 | 1 |   |   | best_ruvsearch_1
1 | covsearch_run15 | (VP1-DOSE-cat) | 0.642644012 | 0.05 | FALSE | FALSE | 21 | 2 |   |   | best_ruvsearch_1
1 | covsearch_run16 | (VP1-SEX-cat) | 0.041739709 | 0.05 | FALSE | FALSE | 20 | 1 |   |   | best_ruvsearch_1

</body>

</html>

And some additional information:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/abrantj1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/abrantj1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

summary_models |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
step | model | description | minimization_successful | errors_found | warnings_found | ofv | runtime_total | estimation_runtime | THETA(1)_estimate | THETA(2)_estimate | THETA(3)_estimate | THETA(4)_estimate | THETA(5)_estimate | THETA(6)_estimate | THETA(7)_estimate | THETA(8)_estimate | OMEGA(1,1)_estimate | OMEGA(2,1)_estimate | OMEGA(2,2)_estimate | OMEGA(3,1)_estimate | OMEGA(3,2)_estimate | OMEGA(3,3)_estimate | OMEGA(4,1)_estimate | OMEGA(4,2)_estimate | OMEGA(4,3)_estimate | OMEGA(4,4)_estimate | SIGMA(1,1)_estimate | POP_KMAGE_estimate | POP_KMBWT_estimate | POP_KMDOSE_1_estimate | POP_KMDOSE_2_estimate | POP_KMSEX_estimate | POP_QP1AGE_estimate | POP_QP1BWT_estimate | POP_QP1DOSE_1_estimate | POP_QP1DOSE_2_estimate | POP_QP1SEX_estimate | POP_VCAGE_estimate | POP_VCBWT_estimate | POP_VCDOSE_1_estimate | POP_VCDOSE_2_estimate | POP_VCSEX_estimate | POP_VP1AGE_estimate | POP_VP1BWT_estimate | POP_VP1DOSE_1_estimate | POP_VP1DOSE_2_estimate | POP_VP1SEX_estimate
0 | best_ruvsearch_1 | time_varying3 | TRUE | 0 | 1 | 2199.740978 | 84 | 77.87 | 290.424 | 0.491661 | 11.9241 | 9782.4 | 37.0854 | 56.8465 | 2.42E-05 | 1.72038 | 0.191432 | 0.163443 | 1.24845 | 0.0325888 | -0.322962 | 0.194103 | 0.0137762 | -0.244172 | 0.207393 | 0.330167 | 0.0302514 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
1 | covsearch_run1 | (KM-AGE-exp) | TRUE | 0 | 1 | 2189.98155 | 81 | 75.01 | 291.315 | 0.4838 | 12.0414 | 9767.39 | 37.7477 | 51.0662 | 2.33E-05 | 1.70703 | 0.190622 | 0.154171 | 1.0818 | 0.0319789 | -0.303171 | 0.186681 | 0.0115095 | -0.216429 | 0.197558 | 0.321429 | 0.0304994 | -0.0305756 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
1 | covsearch_run2 | (KM-BWT-exp) | FALSE | 1 | 0 | 2198.922389 | 137 | 131.18 | 289.765 | 0.494123 | 11.8638 | 9770.38 | 36.8007 | 60.4831 | 2.44E-05 | 1.71865 | 0.191683 | 0.0971425 | 1.11353 | 0.0352386 | -0.31618 | 0.192 | 0.0193333 | -0.216327 | 0.203814 | 0.323883 | 0.0303348 |   | 0.0122099 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
1 | covsearch_run3 | (KM-DOSE-cat) | FALSE | 1 | 0 | 2187.73873 | 93 | 86.04 | 295.145 | 0.467014 | 12.2674 | 9795.57 | 39.1842 | 46.9074 | 2.35E-05 | 1.70036 | 0.191059 | 0.120415 | 1.00407 | 0.028911 | -0.353774 | 0.192237 | 0.00437329 | -0.357418 | 0.203992 | 0.332285 | 0.0306329 |   |   | -0.446684 | 0.885382 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
1 | covsearch_run4 | (KM-SEX-cat) | FALSE | 1 | 0 | 2196.510495 | 128 | 122.16 | 290.613 | 0.490144 | 11.9843 | 9850.66 | 37.1955 | 61.6393 | 2.42E-05 | 1.71526 | 0.19133 | 0.10483 | 1.06111 | 0.032556 | -0.302412 | 0.189069 | 0.014736 | -0.191206 | 0.197639 | 0.308394 | 0.0304364 |   |   |   |   | -0.42427 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
1 | covsearch_run5 | (QP1-AGE-exp) | TRUE | 0 | 1 | 2194.737165 | 92 | 85.98 | 290.889 | 0.48686 | 11.972 | 9804.8 | 37.5351 | 53.6672 | 2.34E-05 | 1.71102 | 0.190566 | 0.155741 | 1.1902 | 0.033132 | -0.32314 | 0.190142 | 0.0129735 | -0.213519 | 0.196688 | 0.323681 | 0.0304248 |   |   |   |   |   | -0.00628559 |   |   |   |   |   |   |   |   |   |   |   |   |   |  
1 | covsearch_run6 | (QP1-BWT-exp) | TRUE | 0 | 1 | 2199.733637 | 95 | 88.36 | 290.559 | 0.491515 | 11.9135 | 9770.4 | 37.106 | 56.8051 | 2.30E-05 | 1.72039 | 0.191384 | 0.162627 | 1.24262 | 0.0342299 | -0.319688 | 0.193707 | 0.0138441 | -0.243513 | 0.207006 | 0.330829 | 0.030249 |   |   |   |   |   |   | -0.000273467 |   |   |   |   |   |   |   |   |   |   |   |   |  
1 | covsearch_run7 | (QP1-DOSE-cat) | FALSE | 1 | 0 | 2193.800058 | 83 | 76.36 | 292.395 | 0.480499 | 12.2694 | 9726.73 | 37.97 | 48.7494 | 2.29E-05 | 1.70232 | 0.191134 | 0.114358 | 0.926684 | 0.0445666 | -0.268408 | 0.161105 | 0.0310732 | -0.199833 | 0.174881 | 0.353867 | 0.0306343 |   |   |   |   |   |   |   | -0.110404 | 0.19166 |   |   |   |   |   |   |   |   |   |   |  
1 | covsearch_run8 | (QP1-SEX-cat) | FALSE | 1 | 0 | 2197.02223 | 66 | 59.99 | 290.648 | 0.490279 | 12.3382 | 9888.19 | 37.187 | 55.2146 | 2.34E-05 | 1.71871 | 0.191614 | 0.162335 | 1.24673 | 0.0177486 | -0.346484 | 0.199275 | 0.00964076 | -0.236142 | 0.20774 | 0.3069 | 0.0303536 |   |   |   |   |   |   |   |   |   | -0.126473 |   |   |   |   |   |   |   |   |   |  
1 | covsearch_run9 | (VC-AGE-exp) | FALSE | 1 | 0 | 2195.697387 | 83 | 77.08 | 292.514 | 0.491867 | 11.9296 | 9760 | 37.1089 | 58.0109 | 2.22E-05 | 1.71704 | 0.203095 | 0.203585 | 1.27351 | 0.0356547 | -0.314139 | 0.190266 | 0.0185784 | -0.224329 | 0.202313 | 0.327073 | 0.0303052 |   |   |   |   |   |   |   |   |   |   | 0.0104776 |   |   |   |   |   |   |   |   |  
1 | covsearch_run10 | (VC-BWT-exp) | FALSE | 1 | 0 | 2168.905472 | 102 | 95.32 | 298.042 | 0.475884 | 12.0865 | 9818.36 | 38.168 | 45.1598 | 1.39E-05 | 1.70184 | 0.0738389 | -0.0155666 | 0.944612 | 0.0491143 | -0.281299 | 0.194652 | 0.0549082 | -0.208524 | 0.212767 | 0.351853 | 0.0305931 |   |   |   |   |   |   |   |   |   |   |   | 0.0191312 |   |   |   |   |   |   |   |  
1 | covsearch_run11 | (VC-DOSE-cat) | TRUE | 0 | 1 | 2193.174394 | 81 | 74.58 | 265.836 | 0.485763 | 11.8434 | 9612.55 | 37.4484 | 53.1298 | 2.33E-05 | 1.70799 | 0.205731 | 0.132938 | 1.00944 | 0.0684405 | -0.278083 | 0.187821 | 0.0761868 | -0.209325 | 0.204695 | 0.34952 | 0.0305024 |   |   |   |   |   |   |   |   |   |   |   |   | 0.32624 | -0.157509 |   |   |   |   |   |  
1 | covsearch_run12 | (VC-SEX-cat) | FALSE | 1 | 0 | 2195.801299 | 74 | 67.63 | 312.644 | 0.484806 | 12.031 | 9838.9 | 37.6751 | 50.2756 | 2.64E-05 | 1.70824 | 0.148786 | 0.0691562 | 1.07274 | 0.0429377 | -0.294636 | 0.192071 | 0.0430807 | -0.218548 | 0.209066 | 0.343572 | 0.0304729 |   |   |   |   |   |   |   |   |   |   |   |   |   |   | -0.294441 |   |   |   |   |  
1 | covsearch_run13 | (VP1-AGE-exp) | TRUE | 0 | 1 | 2198.79221 | 88 | 82.04 | 290.631 | 0.489971 | 11.9476 | 9797.51 | 37.3297 | 55.3191 | 2.39E-05 | 1.71585 | 0.190902 | 0.162324 | 1.22265 | 0.0311873 | -0.31457 | 0.191568 | 0.0100979 | -0.216122 | 0.204972 | 0.333044 | 0.0303511 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 0.00549195 |   |   |   |  
1 | covsearch_run14 | (VP1-BWT-exp) | TRUE | 0 | 1 | 2198.972158 | 69 | 62.88 | 290.417 | 0.492369 | 11.9044 | 9742.1 | 36.9611 | 57.8529 | 2.31E-05 | 1.71919 | 0.192436 | 0.164726 | 1.2803 | 0.033126 | -0.330493 | 0.196188 | 0.0471989 | -0.199532 | 0.204326 | 0.312695 | 0.0302909 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | -0.00554629 |   |   |  
1 | covsearch_run15 | (VP1-DOSE-cat) | TRUE | 0 | 1 | 2198.85665 | 146 | 139.89 | 290.911 | 0.489894 | 11.9113 | 10166.1 | 37.1669 | 56.5235 | 2.33E-05 | 1.72534 | 0.191809 | 0.163689 | 1.28492 | 0.0299961 | -0.342128 | 0.201196 | 0.0125963 | -0.266613 | 0.205766 | 0.297638 | 0.0301612 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | -0.119409 | 0.0358978 |  
1 | covsearch_run16 | (VP1-SEX-cat) | FALSE | 2 | 0 | 2195.595251 | 76 | 70.54 | 290.544 | 0.491136 | 11.9927 | 9278.49 | 37.2352 | 55.1804 | 2.49E-05 | 1.7154 | 0.191804 | 0.160485 | 1.23124 | 0.0319629 | -0.315122 | 0.190238 | 0.0406105 | -0.170933 | 0.193228 | 0.285164 | 0.0304405 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 0.347473

</body>

</html>

**Comment by stellabelin** [comment]
Hi! Thanks for reporting! This does indeed look strange, from the second table it looks like no model was selected and that it didn't move on to the second step. Could you send the error table as well? Found in `res$summary_errors`.

**Comment by joaoabr** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/abrantj1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/abrantj1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



summary_errors |   |   |   |  
-- | -- | -- | -- | --
model | category | error_no | time | message
best_ruvsearch_1 | WARNING | 0 | 00:26.4 | MINIMIZATION SUCCESSFUL
HOWEVER | PROBLEMS OCCURRED WITH THE   MINIMIZATION." |   |   |  
covsearch_run1 | WARNING | 0 | 00:26.4 | MINIMIZATION SUCCESSFUL
HOWEVER | PROBLEMS OCCURRED WITH THE   MINIMIZATION." |   |   |  
covsearch_run10 | ERROR | 0 | 00:26.4 | MINIMIZATION TERMINATED
DUE TO   ROUNDING ERRORS (ERROR=134)" |   |   |  
covsearch_run11 | WARNING | 0 | 00:26.4 | MINIMIZATION SUCCESSFUL
HOWEVER | PROBLEMS OCCURRED WITH THE   MINIMIZATION." |   |   |  
covsearch_run12 | ERROR | 0 | 00:26.4 | MINIMIZATION TERMINATED
DUE TO   ROUNDING ERRORS (ERROR=134)" |   |   |  
covsearch_run13 | WARNING | 0 | 00:26.4 | MINIMIZATION SUCCESSFUL
HOWEVER | PROBLEMS OCCURRED WITH THE   MINIMIZATION." |   |   |  
covsearch_run14 | WARNING | 0 | 00:26.4 | MINIMIZATION SUCCESSFUL
HOWEVER | PROBLEMS OCCURRED WITH THE   MINIMIZATION." |   |   |  
covsearch_run15 | WARNING | 0 | 00:26.4 | MINIMIZATION SUCCESSFUL
HOWEVER | PROBLEMS OCCURRED WITH THE   MINIMIZATION." |   |   |  
covsearch_run16 | ERROR | 0 | 00:26.4 | MINIMIZATION TERMINATED
DUE TO   ROUNDING ERRORS (ERROR=134)" |   |   |  
covsearch_run16 | ERROR | 1 | 00:26.4 | NO. OF SIG. DIGITS UNREPORTABLE
covsearch_run2 | ERROR | 0 | 00:26.4 | MINIMIZATION TERMINATED
DUE TO   ROUNDING ERRORS (ERROR=134)" |   |   |  
covsearch_run3 | ERROR | 0 | 00:26.4 | MINIMIZATION TERMINATED
DUE TO   ROUNDING ERRORS (ERROR=134)" |   |   |  
covsearch_run4 | ERROR | 0 | 00:26.4 | MINIMIZATION TERMINATED
DUE TO   ROUNDING ERRORS (ERROR=134)" |   |   |  
covsearch_run5 | WARNING | 0 | 00:26.4 | MINIMIZATION SUCCESSFUL
HOWEVER | PROBLEMS OCCURRED WITH THE   MINIMIZATION." |   |   |  
covsearch_run6 | WARNING | 0 | 00:26.4 | MINIMIZATION SUCCESSFUL
HOWEVER | PROBLEMS OCCURRED WITH THE   MINIMIZATION." |   |   |  
covsearch_run7 | ERROR | 0 | 00:26.4 | MINIMIZATION TERMINATED
DUE TO   ROUNDING ERRORS (ERROR=134)" |   |   |  
covsearch_run8 | ERROR | 0 | 00:26.4 | MINIMIZATION TERMINATED
DUE TO   ROUNDING ERRORS (ERROR=134)" |   |   |  
covsearch_run9 | ERROR | 0 | 00:26.4 | MINIMIZATION TERMINATED
DUE TO   ROUNDING ERRORS (ERROR=134)" |   |   |  



</body>

</html>
