### ISSUE TITLE
Saddle_reset not present in adm start model

### ISSUE THREAD

**Issue by schaedeli** [pharmpy/pharmpy#1394]
Hi,
I realize that the amd tool generated start model does not include the option SADDLE_RESET=1, which was the default in our previous tests with our own start_model. Is that on purpose? I think the SADDLE_RESET may avoid local minima in some cases which is useful in my opinion. Therefore, I would suggest to include it in the starting model.
Kind Regards
Franziska

**Comment by rikardn** [comment]
Thanks for reporting this. This was a remote regression (a change in another part of the software removed the `SADDLE_RESET` by accident). The fix is in 0.86.0
