### ISSUE TITLE
Handle selected models in hierarchichal tools

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#1502]
When a candidate model has been selected by a subtool, it should be available in its parent directory with a clearer name. For example, in AMD `modelsearch_run1` would be something like `modelsearch_final`. Another example would be when retries have been implemented, the candidate models would have which retry it is, so then it would be clearer if `modelsearch_run1_retry1` becomes `modelsearch_run1` in the modelsearch tool directory.

**Comment by rikardn** [comment]
This now works with the new `Context`
