### ISSUE TITLE
Function update_inits() doesn't work

### ISSUE THREAD

**Issue by zrinkaduvnjak** [pharmpy/pharmpy#1521]
### Bug report

Hi,

I tried to use the update_inits function with pharmR 0.86.0, but it wasn't working for me. I'm not sure if I am using it in the wrong way or if it is a bug. 

Code I used:
run1 <- read_model("run1.mod")
res1 <- read_modelfit_results("run1.mod")

run2 <- run1 %>%
        set_transit_compartments(1) %>%
        set_name("run2")
res2 <- fit(run2)

update_inits(run2, run2$modelfit_results$parameter_estimates)

Warning I got after running the last line:
**/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/parameters.py:307: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if p.name in inits:**

Initials were not changed. After running the last line again I didn't receive the warning, but the initials were still not updated.

I noticed that the order of parameters when I call separately _run2$modelfit_results$parameter_estimates_ and _run2$parameters$inits_ is not identical (if that helps)

**Comment by stellabelin** [comment]
Hi! I tried your example in Pharmpy/pharmr version 0.86.0 and 0.90.0 and could reproduce your error in 0.86.0, while in 0.90.0 it worked as expected, so it should be fixed in the latest release! Closing this issue, please reopen if the error persists.
