### ISSUE TITLE
Support residual error models for multiple dvs

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#1589]
- [x] has_additive_error_model
- [x] has_proportional_error_model
- [x] has_combined_error_model
- [x] additive error
- [x] proportional error
- [x] combined error
- [x] time varying error
- [ ] power
- [x] IIV on RUV

Need to be able to specify which dv has which error model.

**Comment by JohanWBorg** [comment]
As of #1892, the last feature (power) should be implemented
