### ISSUE TITLE
New MFL for drug-metabolite models

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#1591]

**Comment by JohanWBorg** [comment]
Should be implemented as of #2232 
In short, this adds the possibility of setting type of metabolite through `METABOLITE([BASIC,PSC]) `as well as adding a peripheral compartment to the metabolite compartment by adding a second optional argument to `PERIPHERALS(2, MET)`. This argument represent which DVID and therefor compartment the peripherals compartment should be added to. The default option is set to `DRUG
`
