### ISSUE TITLE
Support models with multiple dosing by current transformations

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#1595]
Go through all ode-system transformations and check that multiple dosing is fine.

**Comment by rikardn** [comment]
Zero-order absorption needs

```
IF (ADMID.EQ.1) THEN
    F1 = 1
    ALAG = 0
END IF
```

and changing the RATE column to have 0 for non-oral dosing.

**Comment by JohanWBorg** [comment]
Doses to multiple compartments can now be handled and transformed as wanted after #1837. However, doses to the same compartment is still under development.

**Comment by rikardn** [comment]
Great!
