### ISSUE TITLE
Update add_metabolite function

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#1707]
`add_metabolite` should: 

- [x] Add a metabolite compartment
- [x] Flow from central to metabolite (rate ?)
- [x] Move elimination rate from central compartment to metabolite compartment. (only first order is in scope)
- [x] Have `CLM` be metabolite clearance and `VM` be metabolite volume. (metabolite elimination rate CLM/VM)

- [ ] Have an option "presystemic-fixed-drug" or similar to connect to the compartment before central and scale the rates.
    * New parameter FPRE. (theta limited to [0, 1])   (initial estimate of theta: 0.1)
    * rate depot->metabolite = FPRE*KA, rate depot->central = (1-FPRE)*KA
    * Set bioavailability to 1 / (1 - FPRE) in depot compartment
    * Set IPRED = (A(n) / VM) / bioavail
- [ ] Allow going from plain metabolite compartment to presystemic

**Comment by JohanWBorg** [comment]
As of PR #1944, the remaining features should all have been implemented
