### ISSUE TITLE
Develop structsearch for metabolite models

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#1709]
New tool `structsearch` with metabolite option to perform metabolite model search.

* Starting point is regular PK drug model as output from `modelsearch`.
* Candidates: 1cmp metabolite pre/non-presystemic, 2cmp pre/non-presystemic

**Comment by JohanWBorg** [comment]
As of PR #1944, this should be implemented as described with a new type called "drug_metabolite" in structsearch
