### ISSUE TITLE
Model code changed using fit

### ISSUE THREAD

**Issue by kevin199011** [pharmpy/pharmpy#1722]
Hi, I have a model to fit, however, when using the fit, I noticed the model code was changed leading to running error. I was using the latest pharmpy 0.94.0.
See below, left is original code, right is the code in the modelfit directory.
![image](https://github.com/pharmpy/pharmpy/assets/7540371/6998a3ed-ba3f-446c-b651-d6161efb0a94)
![image](https://github.com/pharmpy/pharmpy/assets/7540371/4e39e4c4-ee1b-4e27-a190-8ed04bce2b4d)
[test.zip](https://github.com/pharmpy/pharmpy/files/11437271/test.zip)

**Comment by stellabelin** [comment]
Hi! Thank you for reporting this! I've added a fix (bb4e404242473aac08bb3182c54d65447e4f81f9), which will not change the model unless the model has been changed. This will be available in the next release. I'll close the issue for now, but if you face any issues you can reopen the issue!

**Comment by stellabelin** [comment]
The new release (0.95.0) is out, so now it should work!
