### ISSUE TITLE
Support allometry for TMDD models

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#1787]
The allometry tool might not be able to detect the parameters correctly.

**Comment by rikardn** [comment]
The allometry tool does not work. The reason is that the `find_clearance_parameters` and `find_volume_parameters` raises.

**Comment by stellabelin** [comment]
Fixed in f2f0106, need to check how to classify clearance parameters for QSS models (does `LAFREE` count as a clearance parameter?)

**Comment by rikardn** [comment]
`LAFREE` is an amount similar to `A(1)`

**Comment by rikardn** [comment]
Perhaps we need to double check that this works?
