### ISSUE TITLE
Error when going from transit CMT to first-order

### ISSUE THREAD

**Issue by cossonvalerie** [pharmpy/pharmpy#179]
I have create the following model manipulation pipeline starting with a 2 cpt model with first order absorption with lagtime as follows: 
$PROBLEM
$INPUT ID TIME AMT DV EVID CMT DOSE FOOD BW SEX BMI AGE STUD TAD
$DATA test_v2.csv IGNORE=@
$SUBROUTINES ADVAN5  TRANS1 
$MODEL COMPARTMENT=(TRANSIT1 DEFDOSE) COMPARTMENT=(TRANSIT2) COMPARTMENT=(TRANSIT3) COMPARTMENT=(DEPOT) COMPARTMENT=(CENTRAL) COMPARTMENT=(PERIPHERAL)
$PK
MDT = THETA(6)
MAT = THETA(1) * EXP(ETA(1))
CL = THETA(2)*EXP(ETA(2))
VC = THETA(3)*EXP(ETA(3))
Q = THETA(4)*EXP(ETA(4))
VP = THETA(5)*EXP(ETA(5))
KA = 1/MAT
V2 = VC
V3 = VP
K12 = 3/MDT
K23 = 3/MDT
K34 = 3/MDT
K45 = KA
K56 = Q/V2
K50 = CL/V2
K65 = Q/V3
$ERROR
CONC = A(5)/VC
Y = CONC + EPS(1)
$ESTIMATION METHOD=COND INTER
$COVARIANCE PRINT=E
$THETA (0, 1, Inf) ; POP_MAT
$THETA (0, 1, Inf) ; POP_CL
$THETA (0, 1, Inf) ; POP_VC
$THETA (0, 1, Inf) ; POP_Q
$THETA (0, 1, Inf) ; POP_VP
$THETA  (0,0.25) ; POP_MDT
$OMEGA 0.1; IIV_MAT
$OMEGA 0.1; IIV_CL
$OMEGA 0.1; IIV_VC
$OMEGA 0.1; IIV_Q
$OMEGA 0.1; IIV_VP
$SIGMA 0.1; RUV_ADD

model <- read_model(model_name)
print(model)

remove_lag_time(model)%>%
  update_source()
print(model)

set_transit_compartments(model,3) %>%
  update_source()

I get an error when I want to go back to a first order model

model <- model %>%
    first_order_absorption()%>%
    update_source()  

#Error in py_call_impl(callable, dots$args, dots$keywords) : 
#  AttributeError: 'NoneType' object has no attribute 'amount'

**Comment by rikardn** [comment]
Thanks for reporting this. I can confirm that this is a bug.
