### ISSUE TITLE
Crash when printing statements for effect compartment models

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#1811]
### Bug report

This should not raise since a user might want to print `model.statements`, perhaps warn and print everything except for ODE system until grid issue has been fixed.

**Comment by rikardn** [comment]
I think we should fix this since it will greatly simplify debugging of these types of models. We should also detect which models cannot be printed and either fallback to printing the equations or print a placeholder.

**Comment by antoniaih** [comment]
Implemented a warning so that the program does not crash when using `model.statements`.

**Comment by stellabelin** [comment]
Closing since there is a warning, if we know specific model types we want to support those can be separate issues.
