### ISSUE TITLE
BIC

### ISSUE THREAD

**Issue by leiwolfm** [pharmpy/pharmpy#1831]
I would like to ask by which method the BIC is calculated in AMD, because I couldn't match it with any of the formulas (BIC=OFV+log(Nobs)P; BICc= OFV+dim(θR)logN+dim(θF)log(ntot) etc).

Thank you very much for your help and your time!

**Comment by stellabelin** [comment]
Hi, thanks for your question! AMD uses different methods (documented [here](https://pharmpy.github.io/latest/api/pharmpy.modeling.calculate_bic.html)) depending on the subtool, it is documented [here](https://pharmpy.github.io/latest/amd.html#structural). `modelsearch` uses `'mixed'`, `iivsearch` uses `'iiv'` and `iovsearch` uses `'random'`, the rest of the tools uses LRT.

**Comment by leiwolfm** [comment]
It's clear now, thank you for the quick response!

**Comment by stellabelin** [comment]
Okay, great! Closing the issue then.
