### ISSUE TITLE
Error when adding plots to bootstrap

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmpy#186]
When calling for plots concerning a bootstrap, the following error appears:
```
res$add_plots()

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  KeyError: 'delta_origdata'
```

Then the parameter estimates histogram is not produced, but something is produced for the parameter estimates correlation plot:
```
res$parameter_estimates_histogram 
NULL

res$parameter_estimates_correlation_plot
```
![image](https://user-images.githubusercontent.com/75365723/116095276-8de14780-a6a8-11eb-9c0e-3810568a2ac4.png)

res$ofv_plot seems to be working fine.

**Comment by rikardn** [comment]
Don't know exactly what is going on here. Could you please file the run directory, the json or both on box?

**Comment by joaoabr** [comment]
Thanks for your response. I have added both the json file and respective folder to box.
