### ISSUE TITLE
Representation of model code in generic model format

### ISSUE THREAD

**Issue by davsjob** [pharmpy/pharmpy#1864]
### Bug report

Using `get_model_code(model)` on a model in generic format version 0.97 yields the code representation below, while in 0.96 it yields error `NotImplementedError: Generic model does not implement the model_code property.`  

Generic model representation:
 `{"parameters": {"parameters": [{"name": "POP_CL", "init": 0.01, "lower": 0, "upper": Infinity, "fix": false}, {"name": "POP_VC", "init": 1.0, "lower": 0, "upper": Infinity, "fix": false}, {"name": "IIV_CL", "init": 0.1, "lower": -Infinity, "upper": Infinity, "fix": false}, {"name": "IIV_VC", "init": 0.1, "lower": -Infinity, "upper": Infinity, "fix": false}, {"name": "sigma", "init": 0.09, "lower": -Infinity, "upper": Infinity, "fix": false}, {"name": "IIV_CL_IIV_VC", "init": 0.01, "lower": -Infinity, "upper": Infinity, "fix": false}, {"name": "POP_MAT", "init": 0.1, "lower": 0.0, "upper": Infinity, "fix": false}, {"name": "IIV_MAT", "init": 0.1, "lower": -Infinity, "upper": Infinity, "fix": false}]}, "random_variables": {"dists": [{"class": "JointNormalDistribution", "names": ["ETA_CL", "ETA_VC"], "level": "IIV", "mean": "MutableDenseMatrix([[Integer(0)], [Integer(0)]])", "variance": "MutableDenseMatrix([[Symbol('IIV_CL'), Symbol('IIV_CL_IIV_VC')], [Symbol('IIV_CL_IIV_VC'), Symbol('IIV_VC')]])"}, {"class": "NormalDistribution", "name": "epsilon_p", "level": "RUV", "mean": "Integer(0)", "variance": "Symbol('sigma')"}, {"class": "NormalDistribution", "name": "ETA_MAT", "level": "IIV", "mean": "Integer(0)", "variance": "Symbol('IIV_MAT')"}], "eta_levels": {"levels": [{"name": "IIV", "reference": true, "group": "ID"}, {"name": "IOV", "reference": false, "group": "OCC"}]}, "epsilon_levels": {"levels": [{"name": "RUV", "reference": true, "group": null}]}}, "statements": {"statements": [{"class": "Assignment", "symbol": "Symbol('MAT')", "expression": "Mul(Symbol('POP_MAT'), exp(Symbol('ETA_MAT')))"}, {"class": "Assignment", "symbol": "Symbol('CL')", "expression": "Mul(Symbol('POP_CL'), exp(Symbol('ETA_CL')))"}, {"class": "Assignment", "symbol": "Symbol('VC')", "expression": "Mul(Symbol('POP_VC'), exp(Symbol('ETA_VC')))"}, {"class": "Assignment", "symbol": "Symbol('KA')", "expression": "Pow(Symbol('MAT'), Integer(-1))"}, {"class": "Assignment", "symbol": "Symbol('V')", "expression": "Symbol('VC')"}, {"class": "CompartmentalSystem", "compartments": [{"class": "Output"}, {"class": "Compartment", "name": "DEPOT", "amount": "Symbol('A_DEPOT')", "dose": {"class": "Bolus", "amount": "Symbol('AMT')", "admid": 1}, "input": "Integer(0)", "lag_time": "Integer(0)", "bioavailability": "Integer(1)"}, {"class": "Compartment", "name": "CENTRAL", "amount": "Symbol('A_CENTRAL')", "dose": null, "input": "Integer(0)", "lag_time": "Integer(0)", "bioavailability": "Integer(1)"}], "rates": [[1, 2, "Symbol('KA')"], [2, 0, "Mul(Symbol('CL'), Pow(Symbol('V'), Integer(-1)))"]], "t": "Symbol('t')"}, {"class": "Assignment", "symbol": "Symbol('IPRED')", "expression": "Mul(Symbol('A_CENTRAL'), Pow(Symbol('VC'), Integer(-1)))"}, {"class": "Assignment", "symbol": "Symbol('IPREDADJ')", "expression": "Piecewise(ExprCondPair(Float('2.2250000000000002e-16', precision=53), Equality(Symbol('IPRED'), Integer(0))), ExprCondPair(Symbol('IPRED'), true))"}, {"class": "Assignment", "symbol": "Symbol('Y')", "expression": "Add(Symbol('IPRED'), Mul(Symbol('IPREDADJ'), Symbol('epsilon_p')))"}]}, "estimation_steps": {"steps": [{"method": "FOCE", "interaction": true, "cov": false, "evaluation": false, "maximum_evaluations": 99999, "laplace": false, "isample": null, "niter": null, "auto": null, "keep_every_nth_iter": null, "solver": null, "solver_rtol": null, "solver_atol": null, "tool_options": {}}]}, "datainfo": {"columns": [], "path": null, "separator": ","}, "value_type": "PREDICTION", "dependent_variables": {"Y": 1}, "observation_transformation": {"Symbol('Y')": "Symbol('Y')"}, "initial_individual_estimates": null, "__magic__": "Pharmpy Model", "__version__": "0.97.0"}`

**Comment by rikardn** [comment]
This has been fixed.
