### ISSUE TITLE
Bug in creating models in estmethod when testing with cov option

### ISSUE THREAD

**Issue by keqiss** [pharmpy/pharmpy#1899]
### Bug report

`res = run_estmethod(algorithm = 'exhaustive',model=model, results=results, covs='all')`

1. The IMP evaluation was added in every model and couldn't be disabled, which makes IMP covariance always output. 
2. The original $EST was overwritten by auto setting e.g. `$ESTIMATION METHOD=COND INTER MAXEVAL=9999 AUTO=1 PRINT=10`, making it impossible to apply $COV with the initial $EST. 

For instance:
```
$ESTIMATION METHOD=IMP INTER MAXEVAL=9999 AUTO=1 PRINT=10
$ESTIMATION METHOD=IMP INTER EONLY=1 MAXEVAL=9999 ISAMPLE=10000 NITER=10 PRINT=10
$COVARIANCE MATRIX=S
```

Pharmpy version: 0.98.2

**Comment by vrognas** [comment]
This issue is really two separate issues. I'll address the first point first.

**Comment by stellabelin** [comment]
There is now an option `compare_ofv` which was added in 01d60ac, setting this to `False` will not add an IMP-evaluation step. Closing the issue.
