### ISSUE TITLE
Implement new Context class

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#1923]
This is a big one.

Context base class:

The context class will be central when running a tool/subtool. It contains the information around the tool to facilitate running its workflow. All tools will have a separate context.

1. ModelDatabase

A reference to the database to use for all models run through this tool. This will be the same for all subtools when running a full workflow.

2. Model names

A map from name to hash of the model database. The names are unique within one context and represent the function the model has in this particular tool. For example "input_model", "candidate1" or "final_model".

3. Results

The regular results object for this tool run.

4. Metadata

The metadata for this tool run.

5. Intermediate results

Any intermediate results or data that doesn't fit in the results object

6. Options

The specific options for this tool run and the global options for all tools run as part of a workflow.

7. Subtool path

The special "path" that determines the place of this subtool in the hierarchy of tools in a workflow.
For example: /amd/iivsearch1/retries1/modelfit1

8. Log

Log for the run

Methods:

model = context.retrive_model(name)
context.store_results(results)
store tool specific file

LocalFileSystemContext:

A subclass of Context that implements the databases in a regular file system

1. Path

File system path

2. Model db symlinks

Symlinks in a separate models directory into the model database

**Comment by stellabelin** [comment]
Need to decide how to handle `description` attribute as well, similar problems as model names have (i.e. different tools need to communicate different things by the description).

**Comment by rikardn** [comment]
This has been implemented
