### ISSUE TITLE
support BLQ column in transform_blq and run_amd

### ISSUE THREAD

**Issue by emiliesg** [pharmpy/pharmpy#1946]
### Feature request

Hi, 
Could you please add an option to support a BLQ column in the dataset via $INPUT when using transform_blq() function or the blq option in run_amd(). Currently, if a BLQ column is present, we get the following error message: unknown column type blq.
Such column is a flag/indicator column, specified as follows: 1=BLQ, 0=not BLQ. It could be combined with an LLOQ column from the dataset or with an lloq value specified as an argument. 
Thanks

**Comment by rikardn** [comment]
I have been working on support for the M5, M6 and M7 methods for BLQ handling. I also added support for a BLQ column, but when reading this issue, I see that it could also be possible to have both a BLQ and an LLOQ column. I guess this makes sense. So are these all the cases:

| case | lloq option | LLOQ column | BLQ column  | Used as indicator | Used as level | Note               |
| ---- | ----------- | ----------- | ----------- | ----------------- | ------------- | ------------------ |
| 1    | Available   | NA          | NA          | DV < lloq         | lloq          |                    |
| 2    | NA          | Available   | NA          | DV < LLOQ         | LLOQ          |                    |
| 3    | NA          | NA          | Available   | BLQ               | nothing       | Only for M1 and M7 |
| 4    | NA          | NA          | NA          | NA                | NA            | No BLQ handling    |
| 5    | NA          | Available   | Available   | BLQ               | LLOQ          | DV column not used |
| 6    | Available   | NA          | Available   | BLQ               | lloq          |                    |
| 7    | Available   | Available   | NA          | DV < lloq         | lloq          | Column overridden  |
| 8    | Available   | Available   | Available   | DV < lloq         | lloq          | Columns overridden |

**Comment by rikardn** [comment]
This is now done. Implemented as in the table.
