### ISSUE TITLE
Deprecation warnings from sphinx when running frem or bootstrap report

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#20]
Deprecation warnings from sphinx when running frem or bootstrap report. Reported upstream: https://github.com/altair-viz/altair/pull/2305

**Comment by rikardn** [comment]
Reproduce with ```pharmpy results report bootstrap_dir1```

**Comment by rikardn** [comment]
The warning is now silenced, but the root problem still needs to be solved.

**Comment by rikardn** [comment]
Fix was merged upstream.

**Comment by rikardn** [comment]
Sphinx 4 has removed the deprecated functions and cannot be used with `altar.sphinxext` in the latest altair on pypi. Reported upstream here: https://github.com/altair-viz/altair/issues/2467

**Comment by rikardn** [comment]
Pharmpy now bundles a patched version of the altairplot sphinx extension. We can go back to the altair version after the next release of altair (see upstream issue linked above)

**Comment by rikardn** [comment]
We could go back to the altair version now, but I think we use jupyter instead now, so perhaps this module could be removed.

**Comment by pharmpy-dev-123** [comment]
@rikardn Still relevant?

**Comment by rikardn** [comment]
I guess the cleanup needed is to go back to go back to the altair version of the extension and remove the bundled version, unless we now only use sphinx and we do not need to switch back to altair.

**Comment by rikardn** [comment]
Handling warnings for the report is a bit back and forth because of so many dependencies. No need to continue tracking as an issue.
