### ISSUE TITLE
error from add_periphral_compartment 

### ISSUE THREAD

**Issue by keqiss** [pharmpy/pharmpy#2060]
### Bug report

When the dataset and model have CMT column even `CMT = DROP`,  `add_periphral_compartment`  sometimes fails which interrupts AMD run and gives errors as shown. When CMT in dataset and model file is deleted then there wouldn't be an error. 

Pharmpy version: 0.101.2

```
2023-09-18 13:18:01,700 - distributed.worker - WARNING - Compute Failed
Key:       PERIPHERALS(1)-add_iivs-choose_best_model-copy-update_inits-run0-2fd0e6fc-e8ea-4e46-b8f9-11a386a3d6b7
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x2b5e08988180>, <pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x2b5dead80910>, (<function _add_iiv_to_func at 0x2b5dea55f380>, 'absorption_delay', (<function _apply_transformation at 0x2b5dea55f100>, ('PERIPHERALS', 1), functools.partial(<function set_peripheral_compartments at 0x2b5dc57b3420>, n=1), (<function update_initial_estimates at 0x2b5dea390180>, (<function _copy at 0x2b5dea55f2e0>, 'modelsearch_run109', (('PERIPHERALS', 1),), (<function _get_best_model at 0x2b5dea55ee80>, <Pharmpy model object modelsearch_run37>, <Pharmpy model object modelsearch_run56>)))))))
kwargs:    {}
Exception: "KeyError('TRANSIT1')"

<Client: 'inproc://172.18.5.6/9736/1' processes=1 threads=16, memory=125.00 GiB>
<Client: 'inproc://172.18.5.6/9736/10' processes=1 threads=16, memory=125.00 GiB>
Traceback (most recent call last):
  File "/crex/proj/pmgroup_active_storage/private/users/keqi/AMDTEST/testrun_mbic2/moxonidine/amdtest.py", line 10, in <module>
    res = run_amd(input = model,
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/tools/amd/run.py", line 266, in run_amd
    subresults = func(next_model)
                 ^^^^^^^^^^^^^^^^
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/tools/amd/run.py", line 363, in _run_modelsearch
    res = run_tool(
          ^^^^^^^^^
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/tools/run.py", line 173, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/tools/run.py", line 220, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, database=tool_database)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/workflows/execute.py", line 73, in execute_workflow
    res: T = dispatcher.run(workflow)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/workflows/dispatchers/local_dask.py", line 80, in run
    res = client.get(dsk_optimized, 'results')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/tools/modelsearch/algorithms.py", line 225, in _apply_transformation
    model = func(model)
      ^^^^^^^^^^^^^^^^^
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/modeling/odes.py", line 1616, in set_peripheral_compartments
    model = add_peripheral_compartment(model)
^^^^^^^^^^^^^^^
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/modeling/odes.py", line 1776, in add_peripheral_compartment
    return model.update_source()
      ^^^^^^^^^^^^^^^^^
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/model/external/nonmem/model.py", line 198, in update_source
    model, updated_dataset = update_statements(
  ^^^^^^^^^^^^^^^^^
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/model/external/nonmem/update.py", line 652, in update_statements
    model, updated_dataset = update_ode_system(model, old_odes, new_odes)
^^^^^^^^^^^^^^^
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/model/external/nonmem/update.py", line 377, in update_ode_system
    model, updated_dataset = update_cmt_column(model, old, new)
      ^^^^^^^^^^^^^^^^^
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/model/external/nonmem/update.py", line 451, in update_cmt_column
    remap[oldmap[dose_comp.name]] = newmap[new.dosing_compartments[0].name]
^^^^^^^
KeyError: 'TRANSIT1'
```

**Comment by rikardn** [comment]
Thanks for reporting. @JohanWBorg is this something you could look at?

**Comment by JohanWBorg** [comment]
Absolutely, I'll see what I can do!

**Comment by JohanWBorg** [comment]
Regarding the first issue that you mentioned, part of the issue seems to be that the model dataset does not match the connected datainfo file. Perhaps the names of the model dataset have been mixed up as the model dataset does not contain a CMT column while the datainfo file does.
Asserting that the model dataset and the datainfo file match will resolve that issue

There seem to be some underlying problem that I am looking further into however :)

**Comment by JohanWBorg** [comment]
#2064 should solve the other part of the first issue where the CMT column could not be updated when the model in question had a non-linear ADVAN (e.g ADVAN13).

Thank you for bringing up that "." was not allowed in the CMT column as well! I am looking into the issue and will update you once it has been solved

**Comment by rikardn** [comment]
"." simply means 0 in a NONMEM dataset and 0 is not allowed

**Comment by JohanWBorg** [comment]
@rikardn So if I am understanding you correctly, we do not want to implement a fix for that error?

**Comment by rikardn** [comment]
The first question is why the "." isn't handled by the parser. So if this model is read in are there "." in the `model.dataset` ?

**Comment by JohanWBorg** [comment]
Yes, and these cause the issue when trying to update the CMT column

**Comment by rikardn** [comment]
So this is a problem with the parser. Is this run using the amd tool? In that case we might only support regular csv-files. Also why did the dataset have a dot in the first place? Could this work with NONMEM?

**Comment by vrognas** [comment]
> So this is a problem with the parser. Is this run using the amd tool? In that case we might only support regular csv-files. Also why did the dataset have a dot in the first place? Could this work with NONMEM?

afaik NONMEM supports dots in the input data, it just replaces it with 0. However, I don't think I've ever seen a dot in the CMT column. What does CMT=0 even mean? 🤷‍♂️

**Comment by keqiss** [comment]
I guess they just want to keep every cell filled with something. When CMT is not necessary for example in a non-dosing or PD record, they sometimes fill it with a dot. It seems common in some data formats to stand for missing or blank.

**Comment by rikardn** [comment]
If we have a NONMEM model as input to a tool then we handle the ".", but if it is only the dataset we cannot. So the error you get is expected.

**Comment by keqiss** [comment]
I did use a model as input, but I guess maybe the error happens before the tool handles the dataset, it was interrupted when creating a dataset with an updated CMT column before model execution.

**Comment by keqiss** [comment]
> So this is a problem with the parser. Is this run using the amd tool? In that case we might only support regular csv-files. Also why did the dataset have a dot in the first place? Could this work with NONMEM?

It is from AMD workflow, and I used .csv dataset.

**Comment by rikardn** [comment]
We managed to figure out that this is not related to the ".". It is about CMT=DROP. A workaround is to remove the dropped CMT-column
