### ISSUE TITLE
Suggestion for more informative documentation on transform_blq()

### ISSUE THREAD

**Issue by schaedeli** [pharmpy/pharmpy#2086]
### Feature request

It would be nice to better understand what the function transform_blq() is actually doing, i.e. for each method, it would be useful to add a sentence what the function is going to change in the model code or the dataset. 
e.g. "m1" will ignore values BLQ, "m3", "m4", add code for estimating the probability of BLQ observations according to [ref], etc.

Furthermore, a warning or information could be included on which method will be implemented, and whether which information on BLQ / LLOQ will actually be used.

**Comment by rikardn** [comment]
Thanks for reporting this. I agree that we should improve the documentation on what the transformation actually does in the different cases.

I am not sure that we should add messages to the function. Perhaps in the cases were it is ambiguous what was used we could warn.

**Comment by antoniaih** [comment]
Added in #2162
