### ISSUE TITLE
Negative lower bounds are converted into 0 in nonmem models

### ISSUE THREAD

**Issue by antoniaih** [pharmpy/pharmpy#2089]
### Bug report

When setting a negative lower bound they get converted into 0 in nonmem models.

**Comment by rikardn** [comment]
This sounds serious is this the case for any initial estimate?

**Comment by antoniaih** [comment]
Sorry, I meant lower bounds, not initial estimates

**Comment by rikardn** [comment]
Ok, so using `set_lower_bounds(model, {'POP_CL': -1})` would generate a NONMEM model with 0 as lower bound?

**Comment by antoniaih** [comment]
Exactly. It works for upper bounds and initial estimates but for some reason it does not work for lower bounds.
It only works if the transformation is performed on a generic model and then converted to a nonmem model.

**Comment by antoniaih** [comment]
It does not work to set any lower bounds, even positive values. That is because lower bounds do not get updated in `update` in pharmpy/model/external/nonmem/records/theta_record.py.

**Comment by antoniaih** [comment]
Fixed in #2099
