### ISSUE TITLE
Add new strictness criteria to modelfit_results

### ISSUE THREAD

**Issue by antoniaih** [pharmpy/pharmpy#2184]
### Feature request

Add the following criteria to modelfit_results so that they can be used in strictness filtering:

- `covstatus`
- `estimate_near_boundary`
- `zero_gradient`
- `condition_number`

**Comment by stellabelin** [comment]
`estimate_near_boundary` is already parsed but need to be added to `warnings`, `condition_number` can be counted on the fly using `numpy.linalg.cond`
