### ISSUE TITLE
Model selection in TMDD structsearch

### ISSUE THREAD

**Issue by antoniaih** [pharmpy/pharmpy#2271]
### Feature request

In structsearch for TMDD models a modelsearch is performed before structsearch. 
After running modelsearch the best model and the best model minus one peripheral compartment is selected. But only successful models are selected. If there is a model with one less compartment but the run failed then this model cannot be used in structsearch.
Maybe in the future it should be implemented that even failed models can be used in structsearch? But how should this be implemented?

**Comment by rikardn** [comment]
I am closing this since it is unclear if this is needed and it would need research to see what would be the best thing to do.
