### ISSUE TITLE
Use Literal in typehints for enum-like strings

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#2279]
For example in `transform_blq`. This could simplify generation of R-code, documentation and trigger better help from the IDE or editor.

**Comment by antoniaih** [comment]
When using Literal in typehints in the subtools no input validation needs to be performed for these arguments because it is already done in `with_runtime_arguments_type_check` in internals/fn/type.py. Hence instead of using e.g. `check_list` we use the function `with_runtime_arguments_type_check`.
