### ISSUE TITLE
Input MFL objects to subfunctions in AMD 

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#2306]
Currently, `mfl_stringify` is made in the subfunctions, e.g:

https://github.com/pharmpy/pharmpy/blob/8c40ac4686b07fbd03417572bef94dc32bd500d2/src/pharmpy/tools/amd/run.py#L457

Instead, `_subfunc_modelsearch` should take an MFL object (and equivalent for other tools that use MFLs).

**Comment by JohanWBorg** [comment]
#2734 should solve this issue
