### ISSUE TITLE
site config directory not correctly set in config.py

### ISSUE THREAD

**Issue by mhacklAimit** [pharmpy/pharmpy#247]
user_path = user_config_dir()
        if user_path.is_file():
            config.read(user_path)
        else:
            site_path = site_config_dir()
            if site_path.is_file():
                config.read(user_path)

 in https://github.com/pharmpy/pharmpy/blob/master/src/pharmpy/config.py

should read 

user_path = user_config_dir()
        if user_path.is_file():
            config.read(user_path)
        else:
            site_path = site_config_dir()
            if site_path.is_file():
                config.read(site_path)

**Comment by mhacklAimit** [comment]
or should I just do this via pull request?

**Comment by stellabelin** [comment]
Hi, thanks for reporting this! Yes, that should be correct. I can change it and it'll be in the next release.
