### ISSUE TITLE
Implement a bottom up algorithm to find number of etas in iivsearch

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#2603]
Procedure:

1. Remove all etas except the eta on clearance giving the model `[CL]`
2. Fit `[CL]`
3. Update inits
4. Create candidates by adding etas to each remaining individual parameter as full blocks giving for example `[CL, VC]`, `[CL, VP1]` and `[CL, QP1]`
5. Run all candidates and select the best model
6. Iterate from 3 (to create for example `[CL, VC, VP1]`
7. When nothing more can be added select the best model by ranking all models with mBIC (or rather the selected ranking method).

This algorithm can be paired with the current `brute_force_block_structure`

This should be possible to run also with linearization. Linearization will require a linearized model to be created as in the top down version. This needs to be used for every step to create the candidate model by removing etas instead of creating. To not have to implement two algorithms the same procedure could also be used for the non-linear option

**Comment by JohanWBorg** [comment]
Implemented in #2695
