### ISSUE TITLE
Use dvid type in datainfo for AMD

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#2699]
Currently there are multiple places where it is hard coded that the dvid column is called DVID, e.g:

https://github.com/pharmpy/pharmpy/blob/c6b8e1ea0d8812893a11bf1040fbc2abbfcdac19/src/pharmpy/tools/amd/run.py#L333

**Comment by antoniaih** [comment]
Needs to be updated in update.py as well:
https://github.com/pharmpy/pharmpy/blob/c6b8e1ea0d8812893a11bf1040fbc2abbfcdac19/src/pharmpy/model/external/nonmem/update.py#L763C9-L777C25
