### ISSUE TITLE
PKPD equations with unusual drug concentration term.

### ISSUE THREAD

**Issue by Orwa-bit** [pharmpy/pharmpy#2726]
Pharmr-v0.103.0

I used the amd tool for a pkpd model where the pk model has a MM elimination:

res_pd = run_amd(input=model_pkpd,
                 modeltype='pkpd',
                 results=model_results,
                 emax_init=80.0,
                 b_init=100.0,
                 ec50_init=1.0,
                 met_init=10.0,
                 order = order1)
                
and I got the following equations for the PD where the PK driver is  A(2) / (A(2) + KM * V) instead of A(2) / V

Direct Emax: E = B * (A(2) * E_MAX / ((A(2) + KM * V) * (A(2) / (A(2) + KM * V) + EC_50)) + 1)
Indirect sigmoid production: DADT(5) = -A(5) * K_OUT + K_IN * (E_MAX * (A(2) / (A(2) + KM * V)) ** N/(EC_50 ** N + (A(2) / (A(2) + KM * V)) ** N) + 1)
Effect compartment sigmoid: DADT(5) = A(2) * KE0 / (A(2) + KM * V) - A(5) * KE0
Effect compartment linear: DADT(5) = A(2) * KE0 / (A(2) + KM * V) - A(5) * KE0
Indirect sigmoid degradation: DADT(5) = -A(5) * K_OUT * (E_MAX * (A(2) / (A(2) + KM * V)) ** N / (EC_50 ** N + (A(2) / (A(2) + KM * V)) ** N) + 1) + K_IN
Indirect linear production: DADT(5) = -A(5) * K_OUT + K_IN * (A(2) * SLOPE / (A(2) + KM * V) + 1)
Indirect Emax production: DADT(5) = -A(5) * K_OUT + K_IN * (A(2) * E_MAX / ((A(2) + KM * V) * (A(2) / (A(2) + KM * V) + EC_50)) + 1)
Direct sigmoid: E = B * (E_MAX * (A(2) / (A(2) + KM * V)) ** N/(EC_50 ** N + (A(2) / (A(2) + KM * V)) ** N) + 1)
Indirect Emax degradation: DADT(5) = -A(5) * K_OUT * (A(2) * E_MAX / ((A(2) + KM * V) * (A(2) / (A(2) + KM * V) + EC_50)) + 1) + K_IN
Indirect linear degradation: DADT(5) = -A(5) * K_OUT * (A(2) * SLOPE / (A(2) + KM * V) + 1) + K_IN
Effect compartment Emax: DADT(5) = A(2) * KE0 / (A(2) + KM * V) - A(5) * KE0
Direct linear: E = B * (A(2) * SLOPE / (A(2) + KM * V) + 1)

**Comment by Orwa-bit** [comment]
Yes it was fixed. I tested it in v0.106.0. Thanks!

**Comment by stellabelin** [comment]
Great, closing the issue.
