### ISSUE TITLE
PKPD models are not being generated in Pharmr-v0.108.0 using run_amd

### ISSUE THREAD

**Issue by Orwa-bit** [pharmpy/pharmpy#2819]
Pharmr-v0.108.0

I was running the code to generate PKPD models (that used to work on versions 0.107 and earlier) and it returned this error: "ValueError: DVID 2 not defined in model".

This is the code I used:

res_pk <- run_amd(input="PK_dataset_filtered.csv",
                   cl_init = init_cl,
                   vc_init = init_vc,
                   mat_init = init_mat, strategy = 'SIR',
                   administration='oral',
                   modeltype = "basic_pk")

model <- read_model('amd_dir1/ruvsearch/models/best_ruvsearch_1/best_ruvsearch_1.ctl')
model_results <- read_modelfit_results('amd_dir1/ruvsearch/models/best_ruvsearch_1/best_ruvsearch_1.ctl')
model_pkpd <- model$replace(dataset=df)

res_pd = run_amd(input=model_pkpd,
                 results=model_results,
                 modeltype='pkpd',
                 search_space="EFFECTCOMP( * );DIRECTEFFECT( * );INDIRECTEFFECT( * , * )",
                 emax_init=80.0,
                 b_init=100.0,
                 ec50_init=1.0,
                 met_init=10.0)

I was able to generate PKPD models using the "run_structsearch" and it did not return any errors.

res_pd <- run_structsearch(type='pkpd',
                        search_space=" EFFECTCOMP( * );DIRECTEFFECT( * );INDIRECTEFFECT( * , * )",
                        model=model_pkpd,
                        results=model_results)

**Comment by antoniaih** [comment]
This is because of the structural covariate step before structsearch.
This is fixed in #2822
