### ISSUE TITLE
PKPD iiv_search: Covariances are tested between PK IIVs and PD IIVs

### ISSUE THREAD

**Issue by Orwa-bit** [pharmpy/pharmpy#2820]
Pharmr-v0.106.0

I was running the code to generate PKPD models:

res_pd = run_amd(input=model_pkpd,
results=model_results,
modeltype='pkpd',
search_space="EFFECTCOMP();DIRECTEFFECT();INDIRECTEFFECT(,)",
emax_init=80.0,
b_init=100.0,
ec50_init=1.0,
met_init=10.0)

During iiv_search, Covariances are tested between fixed PK IIVs and estimated PD IIVs.

**Comment by Orwa-bit** [comment]
This issue has been resolved in v 1.1.0. Thanks!

**Comment by stellabelin** [comment]
Great, closing the issue!
