### ISSUE TITLE
PKPD ruv_search: the RUV is estimated for PK in the final PKPD model

### ISSUE THREAD

**Issue by Orwa-bit** [pharmpy/pharmpy#2821]
Pharmr-v0.106.0

I was running the code to generate PKPD models:

res_pd = run_amd(input=model_pkpd,
results=model_results,
modeltype='pkpd',
search_space="EFFECTCOMP();DIRECTEFFECT();INDIRECTEFFECT(,)",
emax_init=80.0,
b_init=100.0,
ec50_init=1.0,
met_init=10.0)

Following ruv_search, the PK RUV was re-estimated in the final PKPD modes, while all other PK parameters were fixed.

**Comment by Orwa-bit** [comment]
This issue has been resolved in v 1.1.0. Thanks!

**Comment by stellabelin** [comment]
Great, closing the issue!
