### ISSUE TITLE
PKPD ruv_search

### ISSUE THREAD

**Issue by Orwa-bit** [pharmpy/pharmpy#2832]
Pharmr-v0.106.0

Hi, 
we identified bugs in the dataset generated for RUVsearch as part of the AMD run for a PD model using pharmr v0.106. 

The command used for the following: 

res_pd = run_amd(input=model_pkpd,
                 results=model_results,
                 modeltype='pkpd',
                 emax_init=80.0,
                 b_init=100.0,
                 ec50_init=1.0,
                 met_init=10.0,
                 retries_strategy='skip')

structsearch_run12 was identified as the best model following IIVsearch. Here is an except of the NONMEM output table (mytab) corresponding to that run:  

TABLE NO.  1
 ID          TIME        DV          CIPREDI     CWRES       PRED
  3.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00
  3.0000E+00  0.0000E+00  6.3000E+01  8.2822E+01 -1.4091E+00  1.0289E+02
  3.0000E+00  4.8000E-01  3.3230E+01  3.0213E+01  2.1656E-01  1.8633E+01
  3.0000E+00  1.0000E+00  5.5130E+01  4.7070E+01  7.6893E-01  2.7655E+01
  3.0000E+00  1.5000E+00  5.5700E+01  5.3917E+01  4.9166E-01  3.0786E+01
  3.0000E+00  2.0000E+00  5.7830E+01  5.5413E+01  6.5183E-01  3.1239E+01
  3.0000E+00  3.0200E+00  4.3160E+01  5.0565E+01  1.0139E-01  2.8900E+01
  3.0000E+00  3.9800E+00  3.6610E+01  4.2772E+01  7.4807E-02  2.5644E+01
  3.0000E+00  6.0000E+00  3.4400E+01  2.7494E+01  1.1262E+00  1.9309E+01
  3.0000E+00  7.9800E+00  2.4370E+01  1.7190E+01  1.2737E+00  1.4521E+01
  3.0000E+00  1.1980E+01  7.9270E+00  6.5681E+00 -2.5399E-01  8.1658E+00
  3.0000E+00  2.4030E+01  3.5250E-01  4.7908E-01 -1.7924E+00  1.4896E+00
  3.0000E+00  3.6030E+01  1.6680E-01  1.5967E-01 -7.5508E-02  3.2777E-01
  3.0000E+00  4.7020E+01  1.5800E-01  1.4174E-01  2.2701E-01  1.3012E-01
  3.0000E+00  7.1020E+01  1.4910E-01  1.3757E-01  1.2836E-01  7.9785E-02
  3.0000E+00  7.2000E+01  6.4000E+01  7.3908E+01 -1.0049E+00  9.7565E+01
  3.0000E+00  1.6702E+02  1.3070E-01  1.2631E-01 -8.3267E-02  7.1793E-02
  3.0000E+00  1.6800E+02  7.4000E+01  7.5118E+01 -4.1872E-01  9.9599E+01
  3.0000E+00  3.3600E+02  4.5000E+01  7.6633E+01 -2.3679E+00  1.0030E+02
  3.0000E+00  5.0400E+02  4.9000E+01  7.7879E+01 -2.1445E+00  1.0086E+02
  3.0000E+00  6.9600E+02  1.0600E+02  7.9021E+01  1.3914E+00  1.0135E+02
  3.0000E+00  1.1760E+03  8.3000E+01  8.0888E+01 -1.3674E-01  1.0213E+02
  3.0000E+00  1.6080E+03  9.9000E+01  8.1784E+01  7.9104E-01  1.0249E+02
  3.0000E+00  2.1360E+03  8.9000E+01  8.2341E+01  1.6178E-01  1.0271E+02
  4.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00
  4.0000E+00  0.0000E+00  1.3500E+02  1.2826E+02  5.4677E-01  1.0289E+02
  4.0000E+00  5.0000E-01  5.3450E+01  4.2197E+01  1.4171E+00  1.9147E+01
  4.0000E+00  1.0200E+00  6.4880E+01  5.4273E+01  1.1412E+00  2.7859E+01
  4.0000E+00  1.5000E+00  5.5400E+01  5.5128E+01  4.1113E-01  3.0786E+01
  4.0000E+00  2.0000E+00  5.7430E+01  5.2441E+01  6.5777E-01  3.1239E+01
  4.0000E+00  3.0200E+00  3.0660E+01  4.4540E+01 -7.9592E-01  2.8900E+01
  4.0000E+00  4.0300E+00  3.0700E+01  3.7176E+01 -3.4705E-01  2.5473E+01
  4.0000E+00  6.0000E+00  3.3210E+01  2.5981E+01  1.1882E+00  1.9309E+01
  4.0000E+00  7.9800E+00  2.4890E+01  1.8128E+01  1.5027E+00  1.4521E+01
  4.0000E+00  1.1980E+01  9.2600E+00  8.7994E+00  3.5955E-01  8.1658E+00
  4.0000E+00  2.4030E+01  9.8420E-01  1.1173E+00 -2.8984E-01  1.4896E+00
  4.0000E+00  3.6000E+01  3.2400E-01  2.7245E-01  8.6553E-01  3.2885E-01
  4.0000E+00  4.7000E+01  2.3490E-01  1.7884E-01  1.3177E+00  1.3027E-01
  4.0000E+00  7.1030E+01  1.5210E-01  1.6088E-01  5.7201E-02  7.9782E-02
  4.0000E+00  7.2000E+01  1.2900E+02  1.1473E+02  5.2463E-01  9.7565E+01
  4.0000E+00  1.6800E+02  1.0700E+02  1.1714E+02 -4.6461E-01  9.9599E+01
  4.0000E+00  3.3600E+02  1.2300E+02  1.1963E+02  1.8430E-01  1.0030E+02
  4.0000E+00  5.0400E+02  1.3100E+02  1.2161E+02  4.9025E-01  1.0086E+02
  4.0000E+00  6.9600E+02  1.4200E+02  1.2337E+02  9.0974E-01  1.0135E+02
  4.0000E+00  1.1760E+03  1.4700E+02  1.2604E+02  1.0622E+00  1.0213E+02
  4.0000E+00  1.6080E+03  1.3600E+02  1.2719E+02  6.1127E-01  1.0249E+02
  4.0000E+00  2.1360E+03  1.3200E+02  1.2782E+02  4.4337E-01  1.0271E+02
  5.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00
  5.0000E+00  0.0000E+00  8.3000E+01  8.5770E+01 -4.3802E-01  1.0289E+02
  5.0000E+00  5.0000E-01  3.0930E+01  2.5779E+01  7.6750E-01  1.9147E+01
  5.0000E+00  1.0000E+00  3.9890E+01  3.6725E+01  5.4072E-01  2.7655E+01
  5.0000E+00  1.5000E+00  3.6850E+01  4.0216E+01  2.4602E-02  3.0786E+01
  5.0000E+00  2.0000E+00  3.8440E+01  4.0052E+01  1.9113E-01  3.1239E+01
  5.0000E+00  3.0000E+00  2.3680E+01  3.5587E+01 -8.5668E-01  2.8964E+01
  5.0000E+00  4.0000E+00  2.5510E+01  2.9988E+01 -3.1990E-01  2.5576E+01
  5.0000E+00  5.9800E+00  2.4690E+01  2.0596E+01  6.1232E-01  1.9365E+01
  5.0000E+00  7.9800E+00  1.7330E+01  1.3976E+01  4.7173E-01  1.4521E+01
  5.0000E+00  1.1980E+01  8.9570E+00  6.4502E+00  4.8286E-01  8.1658E+00
  5.0000E+00  2.4080E+01  3.2690E-01  7.0507E-01 -2.4229E+00  1.4794E+00
  5.0000E+00  3.6000E+01  1.7340E-01  1.6800E-01  1.7648E-01  3.2885E-01
  5.0000E+00  4.7050E+01  1.3530E-01  1.1597E-01  5.0174E-01  1.2990E-01
  5.0000E+00  7.2000E+01  8.4000E+01  7.9473E+01 -6.4639E-02  9.7565E+01
  5.0000E+00  1.6800E+02  6.8000E+01  8.0618E+01 -1.1326E+00  9.9599E+01
  5.0000E+00  3.3600E+02  6.2000E+01  8.1673E+01 -1.5349E+00  1.0030E+02
  5.0000E+00  4.8000E+02  8.1000E+01  8.2415E+01 -4.1871E-01  1.0078E+02
  5.0000E+00  6.7200E+02  7.5000E+01  8.3208E+01 -8.0948E-01  1.0129E+02
  5.0000E+00  1.1760E+03  8.6000E+01  8.4526E+01 -2.1479E-01  1.0213E+02
  5.0000E+00  1.6080E+03  1.1700E+02  8.5107E+01  1.5609E+00  1.0249E+02
  5.0000E+00  2.1360E+03  8.1000E+01  8.5465E+01 -5.4268E-01  1.0271E+02

base_1.csv is the input dataset used for combined_1.ctl, see below the excerpt. 

MDV	ID	TAD	IPRED	DV
0	3	0	82.721	-1.4232
0	3	0.48	30.282	-1.0311
0	3	1	47.384	-0.44031
0	3	1.5	54.467	-2.4065
0	3	2	56.14	-2.1801
0	3	3.02	51.438	1.3908
0	3	3.98	43.601	-0.14536
0	3	6	28.039	0.79801
0	3	7.98	17.49	0.16516
0	3	11.98	6.6332	0.57482
0	3	24.03	0.47425	0.5155
0	3	36.03	0.15901	-0.48157
0	3	47.02	0.14169	0.18121
0	3	71.02	0.1376	0.49581
0	3	72	74.168	0.92488
0	3	167.02	0.12635	1.0872
0	3	168	75.402	0.6343
0	3	336	76.932	0.46664
0	3	504	78.17	-0.435
0	3	696	79.284	-0.085619
0	3	1176	81.05	-1.1626
0	3	1608	81.86	-1.5657
0	4	2136	82.342	-0.43609
0	4	0	127.91	-0.8274
0	4	0.5	43.116	-0.2193
0	4	1.02	55.189	1.5819
0	4	1.5	55.904	-0.54412
0	4	2	53.092	0.14987
0	4	3.02	45.032	0.87691
0	4	4.03	37.575	0.29233
0	4	6	26.257	0.077351
0	4	7.98	18.32	-0.51899
0	4	11.98	8.8926	0.19665
0	4	24.03	1.1302	0.12647
0	4	36	0.27674	-0.074664
0	4	47	0.18218	-0.17616
0	4	71.03	0.16399	0.43306
0	4	72	114.8	0.67621
0	4	168	117.27	0.54557
0	4	336	119.81	-0.011897
0	4	504	121.79	-0.072577
0	4	696	123.51	-0.21875
0	4	1176	126.02	-0.39826
0	5	1608	127.04	1.0992
0	5	2136	127.58	-0.3816
0	5	0	85.716	0.29315
0	5	0.5	26.008	0.4024
0	5	1	37.073	0.037572
0	5	1.5	40.614	-0.22851
0	5	2	40.458	-0.48005
0	5	3	35.955	-1.0179
0	5	4	30.294	1.1017
0	5	5.98	20.795	-0.6889
0	5	7.98	14.101	0.13881
0	5	11.98	6.4987	-0.61942
0	5	24.08	0.70842	0.009068
0	5	36	0.16954	-0.18997
0	5	47.05	0.11755	-0.53611
0	5	72	79.735	-1.1424
0	5	168	80.89	1.3919
0	5	336	81.94	-0.072472
0	5	480	82.666	0.16241
0	5	672	83.43	-0.60771

We identified the following issues: 
1) the CWRES values in base_1.csv do not match those from mytab. 
2) CWRES corresponding to PK records don't seem to be filtered out in base_1.csv, meaning that the RUVsearch models are built on a CWRES arising from both PK and PD data.
3) Importantly, there is a mismatch between the ID and the TIME column. The first record for ID 4 contains the TIME from the last record of ID 3; the two first records of ID5 contain the TIME from the last 2 records of ID 4, etc. 

Relevant columns from the PKPD dataset used as input to the run_amd() function are as follow: 

ID	AMT	TIME	DV	EVID	DVID	TAD
3	10000	0	0	1	0	0
3	0	0	63	0	2	0
3	0	0.48	33.23	0	1	0.48
3	0	1	55.13	0	1	1
3	0	1.5	55.7	0	1	1.5
3	0	2	57.83	0	1	2
3	0	3.02	43.16	0	1	3.02
3	0	3.98	36.61	0	1	3.98
3	0	6	34.4	0	1	6
3	0	7.98	24.37	0	1	7.98
3	0	11.98	7.927	0	1	11.98
3	0	24.03	0.3525	0	1	24.03
3	0	36.03	0.1668	0	1	36.03
3	0	47.02	0.158	0	1	47.02
3	0	71.02	0.1491	0	1	71.02
3	0	72	64	0	2	72
3	0	167.02	0.1307	0	1	167.02
3	0	168	74	0	2	168
3	0	336	45	0	2	336
3	0	504	49	0	2	504
3	0	696	106	0	2	696
3	0	1176	83	0	2	1176
3	0	1608	99	0	2	1608
3	0	2136	89	0	2	2136
4	10000	0	0	1	0	0
4	0	0	135	0	2	0
4	0	0.5	53.45	0	1	0.5
4	0	1.02	64.88	0	1	1.02
4	0	1.5	55.4	0	1	1.5
4	0	2	57.43	0	1	2
4	0	3.02	30.66	0	1	3.02
4	0	4.03	30.7	0	1	4.03
4	0	6	33.21	0	1	6
4	0	7.98	24.89	0	1	7.98
4	0	11.98	9.26	0	1	11.98
4	0	24.03	0.9842	0	1	24.03
4	0	36	0.324	0	1	36
4	0	47	0.2349	0	1	47
4	0	71.03	0.1521	0	1	71.03
4	0	72	129	0	2	72
4	0	168	107	0	2	168
4	0	336	123	0	2	336
4	0	504	131	0	2	504
4	0	696	142	0	2	696
4	0	1176	147	0	2	1176
4	0	1608	136	0	2	1608
4	0	2136	132	0	2	2136
5	10000	0	0	1	0	0
5	0	0	83	0	2	0
5	0	0.5	30.93	0	1	0.5
5	0	1	39.89	0	1	1
5	0	1.5	36.85	0	1	1.5
5	0	2	38.44	0	1	2
5	0	3	23.68	0	1	3
5	0	4	25.51	0	1	4
5	0	5.98	24.69	0	1	5.98
5	0	7.98	17.33	0	1	7.98
5	0	11.98	8.957	0	1	11.98
5	0	24.08	0.3269	0	1	24.08
5	0	36	0.1734	0	1	36
5	0	47.05	0.1353	0	1	47.05
5	0	72	84	0	2	72
5	0	168	68	0	2	168
5	0	336	62	0	2	336
5	0	480	81	0	2	480
5	0	672	75	0	2	672
5	0	1176	86	0	2	1176
5	0	1608	117	0	2	1608
5	0	2136	81	0	2	2136

Using run_amd() for PKPD in Pharmr-v0.107.0 is only producing structural PD search and not starting the iiv_ nor ruv_search for PD.

**Comment by Orwa-bit** [comment]
This issue has been resolved in v 1.1.0. Thanks!

**Comment by stellabelin** [comment]
Great, closing the issue!
