### ISSUE TITLE
pharmr: PK parameters are not all uniformly referenced  

### ISSUE THREAD

**Issue by SimonBuatois** [pharmpy/pharmpy#286]
Hi, 

I tried to updated a simple PK model and add a dual linear + NL elimination.

When looking at parameter_estimates, parameter_summary etc:

VM/KM parameters are not referenced the same way compare to other parameters: 

![image](https://user-images.githubusercontent.com/75624013/130621034-68945f2f-0818-44a7-ac37-9a6e4a0b65d2.png)

**Comment by rikardn** [comment]
The parameter naming has changed since this issue was raised. Now there are no options for how to give names to avoid coupling the naming to the configuration.
