### ISSUE TITLE
Implement SAMBA in covsearch

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#2953]
The procedure is as follows (only forward search):

0. Prerequisites: Each parameter must have an ETA.
1. Make changes to input model to create a base model:
a) Switch to SAEM with NONMEM options like `METHOD=SAEM AUTO=1 NITER=1000`
b) Request mean for posterior etas
c) mu reference model
2. Estimate base model
3. For each ETA:
a) Create a new dataset having the posterior mean eta values as DV and all covariate values (ID should NOT be in) Don't know if we need to support time-varying covariates. If not one row per individual should be enough
b) Create a base linear (proxy) model.  ```BASE = THETA(1)     Y = BASE + EPS(1)```
c) Estimate the linear base model
d) Add covariate effects to base model
e) Compare each effect model with the base model. The SAMBA paper mentions using AIC or BIC instead of LRT. Don't know if necessary.
4. Select best proxy model
5. Create a non-linear version of the selected model
6. Estimate the non-linear selected model
7. If more effects to test: go to 3 else STOP or continue to backward step (that cannot use SAMBA).

**Comment by JohanWBorg** [comment]
When adding the covariate effects to the non-linear model, the model could require higher amount of evaluations in order to converge properly (probably due to poor initial values). Increasing MAXEVAL seems to solve the issue.

**Comment by rikardn** [comment]
This has been done
