### ISSUE TITLE
model search result for final_model returns NULL

### ISSUE THREAD

**Issue by rosemarychen99** [pharmpy/pharmpy#2986]
### Bug report

Pharmpy version: 0.109.0

tried to retrieve final model of a modelsearch run
`modsearch.result <- read_results("results.json")
modsearch.result$final_model`
But it returns NULL. The result has the path on the cluster is 
/proj/pmgroup_active_storage/private/users/automodeldev/simulation_2024_XC/moxo_sim_structure/modelsearch_dir1
>

**Comment by rosemarychen99** [comment]
The problem still exists for the version 1.0.1

**Comment by stellabelin** [comment]
Hi, thanks for reporting! There is an issue for this so I'll close this one. As a workaround you can perhaps use `retrieve_models` instead?

**Comment by stellabelin** [comment]
See #2188.
