### ISSUE TITLE
Problem with run_iivsearch

### ISSUE THREAD

**Issue by rosemarychen99** [pharmpy/pharmpy#2987]
### Bug report

Pharmpy version: 0.109.0

When running iiv_search, error shows problem with finding ETA or its parameter even though all etas exist in the model. the start model is a final model from a model search run
Screenshot is below. For a full error message, see the file on the cluster: /proj/pmgroup_active_storage/private/users/automodeldev/simulation_2024_XC/moxo_sim_iiv/moxo_sim_iiv.Rout
<img width="950" alt="image" src="https://github.com/pharmpy/pharmpy/assets/35337934/5173862a-0c1a-4ad8-b151-0a73cfdd1d70">

**Comment by rosemarychen99** [comment]
Pharmpy version: 0.110.0

Using the new version, the iivsearch can run. but it still has the problem to detect ETA_CL, so keep option does not work. 
error message
/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/iivsearch/tool.py:457: UserWarning: Parameter CL has no iiv and is ignored
  warnings.warn(f"Parameter {keep} has no iiv and is ignored")

**Comment by stellabelin** [comment]
This should be fixed in https://github.com/pharmpy/pharmr/commit/b7e0b27e805a6e3b96781efb3324a9b10008762f and will be in the next release. There was also a bug in the warning message (fixed in 45e46d2) which obscured the real bug (i.e. from pharmr `c('CL')`) became `['C','L']`.

**Comment by stellabelin** [comment]
A temporary workaround is to write `keep = list("CL")`.
