### ISSUE TITLE
iivsearch json result summary tool missing information

### ISSUE THREAD

**Issue by rosemarychen99** [pharmpy/pharmpy#3033]
### Bug report

Pharmpy version: 0.110.0

the summary tool table retrieved from json in r missing columns of model names and step

**Comment by stellabelin** [comment]
Hi! Thanks for reporting. Is this when you read in the results with `read_results` in R? Does the .csv look correct?

**Comment by rosemarychen99** [comment]
The .csv is correct. But not the summary_tool from `read_results`

> Hi! Thanks for reporting. Is this when you read in the results with `read_results` in R? Does the .csv look correct?

**Comment by stellabelin** [comment]
Okay, I suspect this issue is due to pharmr not resetting the index correctly. Could you send the .json-file or point to it's location?

**Comment by rikardn** [comment]
This was caused by a bug in the pharmr. Fixed here: pharmpy/pharmr@46ae047f6a2ae8ff93442698bea65388b52302d9
Fix will be available in pharmr 1.0
