### ISSUE TITLE
run_amd bug

### ISSUE THREAD

**Issue by rosemarychen99** [pharmpy/pharmpy#3113]
### Bug report

Pharmpy version:1.0.1

> amd.result <- run_amd(input="moxo_sim_data.csv",   # pk dataset, which is formated as NONMEM input dataset
+                       modeltype='basic_pk',        # basic pk models
+                       administration='oral',       # oral PK
+                       cl_init=30,                  # initial value of clearance
+                       vc_init=100,                 # initial value of volume of distribution
+                       mat_init=0.3,                # initial value of mean absorption time, for 1st order absorption, MAT = 1/KA
+                       strategy='default',          # The default run order: structural, iiv, residual, iov, allometry, covariate
+                       allometric_variable='WT',    # the column of body weight for allometric scaling
+                       occasion='VISI',             # the column of occasion for IOV modeling
+                       search_space='LET(CATEGORICAL, [SEX, NYHA,COMP,ACE,DIG,DIU]); LET(CONTINUOUS, [AGE,RF]);COVARIATE?(@IIV,@CONTINUOUS,[LIN,EXP]);COVARIATE?(@IIV,@CATEGORICAL, CAT)')
Full stack:
AttributeError: 'NoneType' object has no attribute 'modes'
AttributeError'NoneType' object has no attribute 'modes'c("  File \"/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py\", line 216, in run_amd\n    to_be_skipped = validate_input(**args)\n", "  File \"/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/internals/fn/type.py\", line 60, in _wrapped\n    return fn(*args, **kwargs)\n", "  File \"/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py\", line 1194, in validate_input\n    if administration == \"oral\" and \"INST\" in (a.name for a in ss_mfl.absorption.modes):\n"
)Traceback (most recent call last):
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py", line 216, in run_amd
    to_be_skipped = validate_input(**args)
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/internals/fn/type.py", line 60, in _wrapped
    return fn(*args, **kwargs)
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py", line 1194, in validate_input
    if administration == "oral" and "INST" in (a.name for a in ss_mfl.absorption.modes):
AttributeError: 'NoneType' object has no attribute 'modes'

pharmr version: 1.0.1
'1.0.1'
Pharmpy version: 1.0.1
This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!

**Comment by rikardn** [comment]
Did this example work in a previous version of Pharmpy?

**Comment by stellabelin** [comment]
Hi! I can reproduce this and confirm it's a bug. A possible workaround is to specify the search space for the modelsearch. The issue is when only the covariate search space is provided, the line that fails relies on the fact that if there is a search space it will have attributes from a structural model search space. Should be fast to fix.
