### ISSUE TITLE
Error with linearization in iiv_search

### ISSUE THREAD

**Issue by yahanhsutw** [pharmpy/pharmpy#3149]
### Bug report

**Pharmpy version**: 1.0.1
**Issue**: When running _iiv_search_ with linearization, there are issues with creating linearized model (same error found when testing the model with _run_linearize_). There were no problem running _iiv_serach_ without linearization.
```
#Run location: /crex/proj/pmgroup_active_storage/private/users/yahan/AMD/iivsearch/daunorubicin/TD_linear/

model_name <- "../base_model/dauno_iivsearch.mod"  #The base model is the final result from "modelsearch" run
model <- read_model(model_name)
model.result <- read_modelfit_results(model_name)

iiv <- run_iivsearch(algorithm = 'top_down_exhaustive',
                     keep = c("CL"),
                     cutoff = NULL,
                     model = model,
                     results = model.result,
                     iiv_strategy = 'fullblock',
                     rank_type = 'bic',
                     strictness = "minimization_successful or (rounding_errors and sigdigs >= 0.1)",
                     correlation_algorithm = NULL,
                     linearize = TRUE) 
```
**Error message**: (full message in iiv_TD_L.Rout)
/domus/h1/yahs1790/.virtualenvs/pharmpy_venv/lib/python3.12/site-packages/pharmpy/tools/iivsearch/tool.py:645: UserWarning: Parameter CL has no iiv and is ignored
  warnings.warn(f"Parameter {keep} has no iiv and is ignored")
<Client: 'inproc://172.18.9.53/9419/1' processes=1 threads=1, memory=6.25 GiB>
2024-06-28 10:07:39,163 - distributed.worker - WARNING - Compute Failed
Key:       create_linearized_model-run0-running_linearization
Function:  execute_task
args:      ((<function postprocess at 0x2afaf0063880>, <pharmpy.workflows.context.local_directory.LocalDirectoryContext object at 0x2afaf209ad80>, 'linear_base_model', <pharmpy.workflows.model_entry.ModelEntry object at 0x2afaf2b05ee0>, (<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x2afaf22af9c0>, <pharmpy.workflows.context.local_directory.LocalDirectoryContext object at 0x2afaf209ad80>, (<function _create_linearized_model at 0x2afaf00639c0>, 'linear_base_model', '[VC,CL,QP1,VP1]', <Pharmpy model object base>, <pharmpy.workflows.model_entry.ModelEntry object at 0x2afaf2b05ee0>))))
kwargs:    {}
Exception: "ValueError('Symbol D_ETA_2 is not defined')"

**Comment by stellabelin** [comment]
Hi! Thanks for reporting. This is a bug, I can recreate this in the integration test when `iiv_strategy='fullblock'`.

**Comment by rikardn** [comment]
I found and fixed multiple issues that stopped linearized iivsearch from running. The development version should work now.
