### ISSUE TITLE
.ext-file not created, possible dataset error

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#329]
For CPT and Daunorubicin the following error occurs when trying to access `minimization_successful` in `modelfit_results`:
```
E   AttributeError: 'NoneType' object has no attribute 'minimization_successful'
```
Looking at the fit-directory, no .ext-file was created and the .lst-file has the following error type for several columns:
```
 (DATA ERROR)      RECORD         1, DATA ITEM   1, CONTENTS: ID
 ITEM IS NOT A NUMBER.
```

**Comment by stellabelin** [comment]
Was successfully run in PsN, maybe something with how Pharmpy writes the dataset

**Comment by rikardn** [comment]
I cannot reproduce this for Daunorubicin. I get the FIX-error, but correcting that makes it run fine.
