### ISSUE TITLE
Issue in R using error_model

### ISSUE THREAD

**Issue by SCarter79** [pharmpy/pharmpy#33]
`pharmpy <- import('pharmpy')
modeling <- import('pharmpy.modeling')

error_model <- modeling$error_model
add_covariate_effect <- modeling$add_covariate_effect

absorption_rate <- modeling$absorption_rate
add_lag_time <- modeling$add_lag_time
update_source <- modeling$update_source

# run1.mod: 1 compartment oral (no lag time or transit compartments)
# Additive residual error (EPS(1))
# No covariance between CL, V and MAT
model1 <- pharmpy$Model('run1.mod')
print(model1)

# i've then used pipe for creation of the second model so that i didn't overwite the first
model2 <- model1 %>% 
  error_model('none') %>%
  #add_lag_time() %>%
  update_source()

# gives the following error:
# Error in py_call_impl(callable, dots$args, dots$keywords) : 
#  AttributeError: 'NoneType' object has no attribute 'update_source'

# if i then run the next part of code, it then removes the error model and adds a lag-time:
model2 <- model1 %>% 
  #error_model('none') %>%
  add_lag_time() %>%
  update_source()

`
RStudio (version 1.1.456), running R 4.0.3, Pharmpy (version: 0.1.0) and Python 3.6.12 from myenv in conda. Original model file saved as .txt so i could upload it here
[run1.txt](https://github.com/pharmpy/pharmpy/files/5554821/run1.txt)

**Comment by rikardn** [comment]
Should be fixed by ade5e50d882536e2249bc4062c22cc53d9672995
