### ISSUE TITLE
Add error message to output

### ISSUE THREAD

**Issue by yahanhsutw** [pharmpy/pharmpy#3326]
### Bug report

**Issue:**
A new type of error message "HESSIAN OF POSTERIOR DENSITY IS NON-POSITIVE-DEFINITE DURING SEARCH" is currently not included in the output csv-file.

**Example file location**: 
/crex/proj/pmgroup_active_storage/private/users/yahan/AMD/iivsearch/tobramycin/TD_linear/iivsearch2/.modeldb/E2c_4pC7hVxNBQWi10j9tTt_JP0zehtBU_5ffuuwPOo/model.lst

**Comment by rikardn** [comment]
Thanks for reporting this issue. I am able to reproduce it.

**Comment by rikardn** [comment]
Fixed with b3eade724f1022c04418fbcd3efba589093bca5e. Fix will be available in the next version.
