### ISSUE TITLE
pkpd error

### ISSUE THREAD

**Issue by rosemarychen99** [pharmpy/pharmpy#3380]
### Bug report

```
> na_pkpd <- run_structsearch(type = "pkpd",
+                             model = start_model,
+                             results = start_model_results,
+                             search_space = "DIRECTEFFECT(*)",
+                             b_init = 400,
+                             emax_init = 600,
+                             ec50_init = 1,
+                             met_init = 1)
```

2024-10-19 08:26:04,997 - distributed.worker - WARNING - Compute Failed
Key:       results
Function:  run_pkpd
args:      (<pharmpy.workflows.context.local_directory.LocalDirectoryContext object at 0x14c242b10>, <Pharmpy model object model>, None, 'DIRECTEFFECT(*)', 400.0, 600.0, 1.0, 1.0, 'minimization_successful or (rounding_errors and sigdigs >= 0.1)')
kwargs:    {}
Exception: 'AttributeError("\'NoneType\' object has no attribute \'parameter_estimates\'")'

<Client: 'inproc://192.168.1.82/1449/1' processes=1 threads=16, memory=32.00 GiB>
Full stack:
AttributeError: 'NoneType' object has no attribute 'parameter_estimates'
Run `reticulate::py_last_error()` for details.AttributeError'NoneType' object has no attribute 'parameter_estimates'c("  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/wrap.py\", line 34, in func\n    return run_tool(tool_name, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/run.py\", line 189, in run_tool\n    return run_tool_with_name(name, tool, args, kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/run.py\", line 248, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/workflows/execute.py\", line 73, in execute_workflow\n    res: T = dispatcher.run(workflow)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 84, in run\n    res = client.get(dsk_optimized, 'results')\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/distributed/client.py\", line 3275, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/distributed/client.py\", line 2372, in gather\n    return self.sync(\n           ^^^^^^^^^^\n", "  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/structsearch/tool.py\", line 201, in run_pkpd\n    baseline_pd_model = create_baseline_pd_model(input_model, results.parameter_estimates, b_init)\n      ^^^^^^^^^^^^^^^^^\n")Traceback (most recent call last):
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/wrap.py", line 34, in func
    return run_tool(tool_name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/run.py", line 189, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/run.py", line 248, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/workflows/execute.py", line 73, in execute_workflow
    res: T = dispatcher.run(workflow)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 84, in run
    res = client.get(dsk_optimized, 'results')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/distributed/client.py", line 3275, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/distributed/client.py", line 2372, in gather
    return self.sync(
           ^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/structsearch/tool.py", line 201, in run_pkpd
    baseline_pd_model = create_baseline_pd_model(input_model, results.parameter_estimates, b_init)
      ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'parameter_estimates'
py_call_impl(callable, call_args$unnamed, call_args$named)c("python.builtin.AttributeError", "python.builtin.Exception", "python.builtin.BaseException", "python.builtin.object", "error", "condition")list(call = list(run_structsearch(type = "pkpd", model = start_model, results = start_model_results, search_space = "DIRECTEFFECT(*)", b_init = 400, emax_init = 600, ec50_init = 1, met_init = 1), tryCatch({
    func_out <- pharmpy$tools$run_structsearch(type, search_space = search_space, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, results = results, model = model, extra_model = extra_model, strictness = strictness, extra_model_results = extra_model_results, dv_types = dv_types, ...)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_structsearch(type, search_space = search_space, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, 
    met_init = met_init, results = results, model = model, extra_model = extra_model, strictness = strictness, extra_model_results = extra_model_results, dv_types = dv_types, ...), py_call_impl(callable, call_args$unnamed, call_args$named)), parent = c(0, 1, 2, 3, 4, 3, 6, 7, 1, 9), visible = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), namespace = c("pharmr", "base", "base", "base", "base", "base", "base", "base", NA, "reticulate"), scope = c("::", "::", "local", "local", "local", 
"local", "local", "local", NA, ":::"), full_call = list(run_structsearch(type = "pkpd", model = start_model, results = start_model_results, search_space = "DIRECTEFFECT(*)", b_init = 400, emax_init = 600, ec50_init = 1, met_init = 1), tryCatch({
    func_out <- pharmpy$tools$run_structsearch(type, search_space = search_space, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, results = results, model = model, extra_model = extra_model, strictness = strictness, extra_model_results = extra_model_results, dv_types = dv_types, ...)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_structsearch(type, search_space = search_space, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, 
    met_init = met_init, results = results, model = model, extra_model = extra_model, strictness = strictness, extra_model_results = extra_model_results, dv_types = dv_types, ...), py_call_impl(callable, call_args$unnamed, call_args$named)))
pharmr version: 1.2.0
'1.2.0'
Pharmpy version: 1.2.0
This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!

**Comment by rikardn** [comment]
Thanks for reporting. It is a bug. It seems as if the results you send in is `NULL` and this cannot be handled. Could you check if that is the case?

**Comment by rikardn** [comment]
I have now made the `results` option mandatory for `structsearch` so you would in the next version get a proper error message instead.
