### ISSUE TITLE
Issue with write_model in python

### ISSUE THREAD

**Issue by SCarter79** [pharmpy/pharmpy#34]
I took the first model, copied it and made some changes to the error model. I then tried to write the second model as a new file (run2.mod), but python tells me run1.mod already exists.
`# load packages
from pharmpy import * 

# load and check base model
# Oral 1 compartment (ADVAN2 TRANS2)
# Additive residual error model
model1 = Model('run1.mod')

# copy model1 so that we don't overwite run1.mod
model2 = model1.copy()

# change error model and initial estimate for EPS(1)
from pharmpy.modeling import error_model
from pharmpy.modeling import update_source

error_model(model2,'proportional')
Parameter('EPS(1)',0.1)
update_source(model2)

# check update
modsumm2 = model2.statements
print(modsumm2)

# write to run2.mod
from pharmpy.modeling import write_model
write_model(model2,'run2.mod')
`

and this is the error i got:
`
---------------------------------------------------------------------------
FileExistsError                           Traceback (most recent call last)
<ipython-input-38-4422b5eea394> in <module>
     16 # write to run2.mod
     17 from pharmpy.modeling import write_model
---> 18 write_model(model2,'run2.mod')
     19 

~\Anaconda3\envs\pharmpytest\lib\site-packages\pharmpy\modeling\common.py in write_model(model, path, force)
     12 def write_model(model, path='', force=False):
     13     """Write model to file"""
---> 14     model.write(path='', force=False)
     15     return model
     16 

~\Anaconda3\envs\pharmpytest\lib\site-packages\pharmpy\model.py in write(self, path, force)
     71             new_name = path.stem
     72         if not force and path.exists():
---> 73             raise FileExistsError(f'File {path} already exists.')
     74         if new_name:
     75             self.name = new_name

FileExistsError: File run1.mod already exists.
`
Running conda, with python 3.6.12 and pharmpy 0.1.0

**Comment by rikardn** [comment]
Thanks for reporting this! It is a bug. A workaround is to use the write method instead:

```python
model2.write('run2.mod')
```
