### ISSUE TITLE
run_amd for basic_pk with strategy = 'SIR' completed only modelsearch and IIVsearch

### ISSUE THREAD

**Issue by Orwa-bit** [pharmpy/pharmpy#3416]
### Bug report

Pharmpy/pharmr v1.3.0

I used the following to run_amd for basic_pk:

res_pk <- run_amd(input="PK.csv",
                  cl_init = init_cl,
                  vc_init = init_vc,
                  mat_init = init_mat,
                  strategy = 'SIR',
                  administration='oral',
                  modeltype = "basic_pk")
                  
This only generated modelsearch and IIV search. It did not proceed to RUV search with no BUG report.
This was resolved when I changed  strategy = 'SIR' to strategy = 'default'.

**Comment by stellabelin** [comment]
Hi! Thanks for reporting this, it was a regression from 5873fe9 and will be fixed in the next release.
