### ISSUE TITLE
NONMEM model changes

### ISSUE THREAD

**Issue by SCarter79** [pharmpy/pharmpy#35]
When a NONMEM model is edited (run1.mod) in pharmpy and then written as a second NONMEM model (run2.mod) there is a slight copy paste issue.
`
### run1.mod (additive residual error)

$PK
;---------- PK model --------------

CL    = THETA(1)*EXP(ETA(1))  ; Typical CL value
V     = THETA(2)*EXP(ETA(2))  ; Typical V value
MAT   = THETA(3)*EXP(ETA(3))  ; Typical MAT value
K     = CL/V
KA    = 1/MAT
VC    = V

$ERROR
PRED = A(2)/VC
CONC = PRED
Y = CONC + EPS(1)

### run2.mod (proportional residual error
$PK
;---------- PK model --------------

CL    = THETA(1)*EXP(ETA(1))  ; Typical CL value
V     = THETA(2)*EXP(ETA(2))  ; Typical V value
MAT   = THETA(3)*EXP(ETA(3))  ; Typical MAT value
K     = CL/V
KA    = 1/MAT
VC    = V

$ERROR
PRED = A(2)/VC
CONC = PRED
Y = EPS(1)*F + F
`
I'm not sure if this will make a difference in the run

**Comment by rikardn** [comment]
I confirmed that c06272415a2a4d1654f2c0613aa3796c4693db08 indeed solves this by adding extra unit tests 739c7f658f338e0e387b8e37571d5d0f637624f4
