### ISSUE TITLE
Sporadic timeout of connection on cluster

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#386]
When running on the cluster, sometimes the following error is raised:
```
OSError: Timed out trying to connect to inproc://... after 30 s
distributed.comm.inproc - WARNING - Closing dangling queue in <InProc  local=inproc://... remote=inproc://...>
```
It seems to be sporadic, appears for e.g. the warfarin model. Warning does not appear every time.

**Comment by rikardn** [comment]
Is pharmpy run inside a SLURM allocation? I guess it must allocate an entire node as that is currently what Pharmpy asks dask to do. Don't know if this could explain the issue though.

**Comment by stellabelin** [comment]
It's via the `srun`command

**Comment by stellabelin** [comment]
This hasn't occurred since this issue as far as I'm aware, maybe this can be closed @rikardn?

**Comment by rikardn** [comment]
I haven't heard of this happening again. Closing
