### ISSUE TITLE
Proportional error models

### ISSUE THREAD

**Issue by SCarter79** [pharmpy/pharmpy#39]
currently the following code is generated for NONMEM:

```
$PK
;---------- PK model --------------

CL    = THETA(1)*EXP(ETA(1))  ; Typical CL value
V     = THETA(2)*EXP(ETA(2))  ; Typical V value
MAT   = THETA(3)*EXP(ETA(3))  ; Typical MAT value
K     = CL/V
KA    = 1/MAT
VC    = V

$ERROR
IPRED = A(2)/VC
CONC = IPRED

Y = CONC*EPS(1) + CONC 
```

however this will not run, the code needs and extra couple of lines, note the order of Y as well - i think it is more common to have the prediction without the EPS(1) first?

```
$PK
;---------- PK model --------------

CL    = THETA(1)*EXP(ETA(1))  ; Typical CL value
V     = THETA(2)*EXP(ETA(2))  ; Typical V value
MAT   = THETA(3)*EXP(ETA(3))  ; Typical MAT value
K     = CL/V
KA    = 1/MAT
VC    = V

$ERROR
IPRED = A(2)/VC
CONC = IPRED
W = CONC
IF(CONC.EQ.0)W = 1

Y = CONC + W*EPS(1) 
```

**Comment by rikardn** [comment]
Thanks!  The note about the printing order is in this issue: https://github.com/pharmpy/pharmpy/issues/23

**Comment by rikardn** [comment]
We could use `(ONLY OBSERVATION)` in the `$ERROR` for models that we control. For other models perhaps we could check if DV<=0 or similar to see if this is a non-observation, but I don't know to create a more general solution that works also for PRED models for example.

**Comment by SCarter79** [comment]
This was an issue with data from one individual, it runs fine on the rest, so i'll close this as an issue

**Comment by rikardn** [comment]
Reopen to think about a general solution to the observation issue.

**Comment by rikardn** [comment]
This has been fixed with zero protection code
