### ISSUE TITLE
append_estimation_step_options: example does not work

### ISSUE THREAD

**Issue by emiliesg** [pharmpy/pharmpy#396]
model <- load_example_model("pheno")
opts <- list('NITER'=1000, 'ISAMPLE'=100)
append_estimation_step_options(model, tool_options=opts, idx=0)

outputs the following error: 
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: list indices must be integers or slices, not float

**Comment by stellabelin** [comment]
This was fixed in Pharmpy/Pharmr 0.36.0.
