### ISSUE TITLE
add_iiv(): logit option does not give expected output

### ISSUE THREAD

**Issue by emiliesg** [pharmpy/pharmpy#397]
model <- load_example_model("pheno")
remove_iiv(model, "CL")
add_iiv(model, "CL", "logit") 

gives the following NONMEM code: 
cat(model$model_code)

[...]
$PK
IF(AMT.GT.0) BTIME=TIME
TAD=TIME-BTIME
TVCL=THETA(1)*WGT
TVV=THETA(2)*WGT
IF(APGR.LT.5) TVV=TVV*(1+THETA(3))
CL = TVCL*LOGIT
V = TVV*EXP(ETA(1))
S1=V
[...]

Here LOGIT is not defined and the NONMEM model won't run.

**Comment by stellabelin** [comment]
Hi! Thanks for reporting this! Yes, it looks like the documentation is wrong, it should be `log` instead of `logit`.
