### ISSUE TITLE
THETA Parsing Error

### ISSUE THREAD

**Issue by billdenney** [pharmpy/pharmpy#4]
I am getting a parsing error for the $THETA block.

I can't readily share the full model, but the beginning of the $THETA block is:

```
$THETA
 ;; Model characteristics
 (0, 0.15, 0.6) ; Proportional
```

I'm using version 0.2.0, and the error I'm getting is:

```
> model <- pharmpy$Model("run3.mod")
> model$parameters
Error in py_get_attr_impl(x, name, silent) : 
  UnexpectedCharacters: No terminal defined for ';' at line 2 col 2

 ;; Model characteristics
 ^

Expecting: {'NUMERIC', 'LPAR'}
> 
```

**Comment by rikardn** [comment]
Thanks for reporting this! For parser errors such as this the full model won't be needed. I'll have a look.

**Comment by billdenney** [comment]
I was hoping that the full model wasn't required.  :)

I'm guessing that the important detail is that I have a comment line that is not related to a THETA record.  The model is big-ish, so I have sections within the $THETA block separated by comments.

**Comment by rikardn** [comment]
I can reproduce the problem.

**Comment by billdenney** [comment]
As an aside, I'm also using similar comments within the $OMEGA block (and theoretically, I could use them within the $SIGMA block, but I'm not doing so in this model).  When you find the fix, can you please also apply it to those sections if they would have the same problems?

**Comment by rikardn** [comment]
I had actually already found and fixed these types of problems in the $OMEGA/$SIGMA, but I didn't realize that the same problems would apply to $THETA.

**Comment by rikardn** [comment]
@billdenney I'll email you an updated source package in case you want to test. I plan to do a proper release next week.
