### ISSUE TITLE
Unsuccessful minimization during Model search

### ISSUE THREAD

**Issue by Alzahra-Hamdan** [pharmpy/pharmpy#423]
For model search tool, candidate models with unsuccessful minimization are still reported and transformed to the next layer. The search run is ending with an error without reporting any results for successful runs. 

<img width="530" alt="Capture" src="https://user-images.githubusercontent.com/93916031/143026313-f90785d4-21b2-440f-b938-6c87a3c943d7.PNG">

**Comment by stellabelin** [comment]
NONMEM gives an estimate that is out of bounds, in modelsearch it should skip this model instead of doing update_inits

**Comment by stellabelin** [comment]
Solved in 9117c7111a840b747c5fbb4fb6b86842f1678ae3.
