### ISSUE TITLE
LOG transformation

### ISSUE THREAD

**Issue by Alzahra-Hamdan** [pharmpy/pharmpy#424]
The pharmpy function for setting a proportional error model with log transformed data is not able to handle zero values.
For example: `set_proportional_error_model(model, data_trans='log(Y)')` results in: 
`$ERROR
CONC = A(2)/VC
Y = LOG(CONC) + EPS(1)`

**Comment by rikardn** [comment]
Thanks for reporting this. I have been thinking of different solutions. The most robust I can think of is to add

```
IF CONC.EQ.0 THEN
    CONC = 2.225e-307     ; smallest possible positive double precision float
END IF
```
