### ISSUE TITLE
Pretty printing of models

### ISSUE THREAD

**Issue by SCarter79** [pharmpy/pharmpy#46]
When adding transit compartments, the printed output adds multiple depots:
`# Import packages
from pharmpy import *
from pharmpy.modeling import set_transit_compartments
from pharmpy.modeling import update_source

# copy model1 so that run1.mod is not overwritten
model1 = Model('run1.mod')
model4 = model1.copy()

# add 2 transit compartment
set_transit_compartments(model4,2)
update_source(model4)

modsumm4 = model4.statements
print(modsumm4)`
![image (1)](https://user-images.githubusercontent.com/40889227/100333121-8111d800-2fd2-11eb-9842-6dab77b68b66.png)
![image](https://user-images.githubusercontent.com/40889227/100333123-82430500-2fd2-11eb-975c-a245271da4d9.png)

**Comment by rikardn** [comment]
I can confirm that this is a bug
