### ISSUE TITLE
Dropped RATE-column should be used when changing to ZO abs

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#493]
If a model has a dropped RATE-column and `set_zero_order_absorption` adds a RATE-column, the previous one should be replaced.

**Comment by rikardn** [comment]
b313d2935e51b4aaa31c8930862bfb89ae6a01a0 will not use a dropped RATE column when reading the dose information for a NONMEM model. Code might still be needed for replacing the dropped column if needed.

**Comment by stellabelin** [comment]
Replaced by #751
