### ISSUE TITLE
Duplicated ETA in SEQ-ZO-FO model when using add.etas option in model search

### ISSUE THREAD

**Issue by Alzahra-Hamdan** [pharmpy/pharmpy#517]
$OMEGA X IIV_MAT is duplicated in SEQ-ZO-FO models when having `add.etas=TRUE` during model search. This results in including this parameter twice in COV MATRIX FOR RANDOM EFFECTS.
<img width="544" alt="Capture1" src="https://user-images.githubusercontent.com/93916031/151010086-7e01f609-e0c2-45c4-8423-dba09741c676.PNG">
<img width="403" alt="Capture2" src="https://user-images.githubusercontent.com/93916031/151010112-c7dbfda2-577b-4472-a303-527d748d6358.PNG">
.

**Comment by stellabelin** [comment]
Hi! Thank you for reporting! I cannot reproduce this behavior on the moxonidine model at least, which model are you using and what does your code look like?

**Comment by Alzahra-Hamdan** [comment]
Hi! I am working on Desmopressin dataset, I can send you the starting model and dataset through email.

**Comment by stellabelin** [comment]
Great, thank you!

**Comment by stellabelin** [comment]
This should be fixed in aa2a3e62ece27276661fc3a4c38504664586ead7. Closing the issue, please reopen it if it persists in the new release!
