### ISSUE TITLE
$DES not generated when using ZO or MM elimination transformations for P1 models

### ISSUE THREAD

**Issue by Alzahra-Hamdan** [pharmpy/pharmpy#528]
When setting MM or ZO elimination for models with 2 comp., the $DES is not generated (as shown in the model file code).
<img width="381" alt="set_MM" src="https://user-images.githubusercontent.com/93916031/152993253-58502b1c-669a-47e7-91bc-e62385a9691e.PNG">
<img width="388" alt="genta_P1-MM" src="https://user-images.githubusercontent.com/93916031/152993256-6fba596d-e069-4241-a771-274f171ca7ec.PNG">

**Comment by rikardn** [comment]
I cannot reproduce with another ADVAN3 model. Could you please send the model to me
