### ISSUE TITLE
Introducing an upper limit for KM parameter

### ISSUE THREAD

**Issue by Alzahra-Hamdan** [pharmpy/pharmpy#541]
When having ZO, MM, and MIX-FO-MM elimination in search space, MS run fails for having high estimates of KM.
A solution to overcome this issue is to introduce an upper limit for KM = 20* highest DV.
![Picture1](https://user-images.githubusercontent.com/93916031/154456916-5aa32f34-18b5-4110-851b-dc5133f3797b.png)

**Comment by rikardn** [comment]
I don't think it would help with this problem. NONMEM has an implicit upper bound of 1e6 if nothing else was specified (all bounds are presented in the lst-file). This will also be used if `inf` was used as an upper bound. It seems as if NONMEM violates the parameter bound here for some reason. Have you tried that it would work to set an explicit bound?

**Comment by Alzahra-Hamdan** [comment]
Yes. In this example error: the high value is coming from the KM final estimate for MM candidate: `3.60E+11`.
I tried to run this model with introducing upper bound `$THETA  (0,2736.6, 27360) ; POP_KM`, the final estimate is now `2.71E+04 `. So, this should help in updating initials and transforming for next candidate without generating this error.

**Comment by rikardn** [comment]
Ok, good (although strange). Then we will set an upper bound.
