### ISSUE TITLE
ETA on CLMM

### ISSUE THREAD

**Issue by Alzahra-Hamdan** [pharmpy/pharmpy#542]
In nonlinear elimination transformations, the added CLMM parameter doesn't have ETA.
 So, for example in MM, the starting model is having IIV_CL while in MM model no IIV_CLMM is replacing this ETA.

**Comment by rikardn** [comment]
Makes sense. I.e. CLMM will replace CL except for the mixed FO-MM cases.

**Comment by rikardn** [comment]
This should be solved by f55e3388fa8eda2c14825c61c63193d0a52ddb55
