### ISSUE TITLE
Output after fit()

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmpy#552]
Hi,

After a model is estimated using the fit() function, the NONMEM model is copied into the Console. Would it be possible to instead output the final iteration and the minimization status so that the user knows whether or not the model converged?

Also, could a function be created giving the summary output of the relevant parameters (OFV, parameter estimates, etc.) as seen in PsN sumo?

**Comment by rikardn** [comment]
This issue has three issues in one. I keep it for the first issue only and created #550 and #551 for the other two.

**Comment by rikardn** [comment]
The fit function now returns the `ModelfitResults` object. Closing
