### ISSUE TITLE
Initial estimates for additive error can be 0 and cause crash

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#56]
If DV min is 0 the initial estimate for the additive error is set to 0, and the following is raised:

`pharmpy.model.ModelSyntaxError: If initial estimate for <built-in method upper of str object at 0x7fb35965a1b0> is 0 it must be set to FIX`

See e.g. run168.mod.

**Comment by rikardn** [comment]
First the error message is buggy. It should print the parameter name instead of `<...>`

In this case we really do not want 0 as the init so I think the transformation should disallow 0 and set some small value instead.
