### ISSUE TITLE
Copy changed datasets in tools

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#579]
Copy any datasets that are different from original to model database

**Comment by rikardn** [comment]
One suggestion is to have the datasets in a separate directory in tool directory like:

```
modelsearch_dir1/
    models/
    datasets/
```

and we only put the various different datasets there and set the path in $DATA appropriately. This way it is clear that datasets have been stored and we can even have an option to not store them (PsN has a similar option)

**Comment by rikardn** [comment]
An updated suggestion to be able to use the model database also for datasets:

```
modelsearch_dir1/
    models/
        .datasets/
```

**Comment by rikardn** [comment]
We should also store datainfo here and compare it before the dataframe to check for differences.
