### ISSUE TITLE
Can't find IDV label for some models

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#58]
When changing to an additive error model, pharmpy crashes for some models when choosing initial estimate while trying to access dataset observations:

```
self = <pharmpy.data.data_frame.LabelsByTypeIndexer object at 0x7fb33e556700>, tp = ColumnType.IDV

    def _get_one_label(self, tp):
        labels = self._get_many_labels(tp)
        if len(labels) == 0:
>           raise KeyError(str(tp))
E           KeyError: 'ColumnType.IDV'
```

See e.g. run13.mod.

**Comment by rikardn** [comment]
This is a `$PRED` model and NONMEM doesn't enforce `TIME` as the idv column as for `$PK` models. The user is free to use any column as idv. We could assume `TIME` to be the idv by default even for these models and make it possible to override this if given a dataset metadata file.
