### ISSUE TITLE
Suggestion: Use %import to standardize grammars

### ISSUE THREAD

**Issue by billdenney** [pharmpy/pharmpy#6]
As noted in #4 , there was something fixed in $OMEGA that was not in $THETA.

It looks like the lark `%import` directive could help with standardizing some parts across the NONMEM grammars.  For example, the "common misc rules", "common misc terminals", and "common numeric terminals" could be standardized across several of the grammars and thereby ensure that bugs fixed one place benefit all.

References:
https://lark-parser.readthedocs.io/en/latest/grammar/
https://dev.to/vicentemaldonado/python-lark-parser-introduction-2g4e

**Comment by rikardn** [comment]
Thanks for pointing this out. I have moved common terminals from all grammars to definitions.lark. We will also consider having common rules in the future.
