### ISSUE TITLE
Parser Fails with Symbolic Thetas

### ISSUE THREAD

**Issue by billdenney** [pharmpy/pharmpy#67]
I have a model that uses symbolic `THETA()` values with `$ABBR REPLACE`.  I was playing around with pharmpy via R, and I got an error where it appears that the parser was expecting an integer.

I had to subtly change the message so that it masks the underlying model:

```r
> models[[1]]$to_base_model()
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  UnexpectedCharacters: No terminal defined for 'L' at line 7 col 23

  LTVCL   = THETA(LTVCL)
                  ^

Expecting: {'WS', 'INTEGER'} 
```

The model has a line like the following

```
$ABBR REPLACE THETA(LTVCL)=THETA(1)
```

**Comment by rikardn** [comment]
Thanks for reporting this. Pharmpy doesn't yet support `$ABBR`. I don't think it would be too difficult to add support though.

**Comment by rikardn** [comment]
A first step 2b3333090acc516f1bfe5ee9163541cea6a4eac5 handles parsing of `$ABBR`.

**Comment by stellabelin** [comment]
Configuration is now possible to parse and write $ABBR (5b171074403170eef84aafce81f6a06734c19ce1 and feceb126d0aa5b7e376d8d831d97439f01652360)
