### ISSUE TITLE
Reduced model search algorithm at layer 3 is not working

### ISSUE THREAD

**Issue by Alzahra-Hamdan** [pharmpy/pharmpy#694]
The reduced exhaustive algorithm seems not working when moving from layer 3 to layer 4 (so 24 models in layer 4 were generated instead of only 8).
For example, the following models are produced at layer 4 where their parent models are actually the samebut from different routes:
1/ A(ZO)-P1-E(MIX)-LAG
2/ A(ZO)-E(MIX)-P1-LAG
3/ P1-E(MIX)-A(ZO)-LAG

**Comment by stellabelin** [comment]
This is using the full search space
