### ISSUE TITLE
long post-process time when running run_iiv

### ISSUE THREAD

**Issue by rosemarychen99** [pharmpy/pharmpy#697]
It took 4 minutes to finished all the models in both the steps. But the post-process for the 2nd step took 12 min. Here are the time line:
The run started: 3:52pm

All the models in the 1st step finished: 3:53pm
The 1st step finished: 3:54pm

All the models in the 2nd step finished: 3:56pm
The 2nd step finished: 4:08pm

Please contact me if you need the related model.

**Comment by stellabelin** [comment]
Thanks for reporting! How many models were generated in each step? In the latest release (0.64.1) I have made a change to speed up the post-processing which should help, and if there are more models it will obviously make it slower in general but the relationship is not linear, so more models will lead to much slower post processing time.

**Comment by rosemarychen99** [comment]
Hi, I rerun it using the newest version (0.64.1). Now the post-process time is short (~1 min). Thanks!
