### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by Mutaz94** [pharmpy/pharmpy#702]
Hi @rikardn 

Great work with pharmpy. I'm curious what is the contribution guidelines for this project? Any TODO list other than issues? I'm happy to chime in. 

Mutaz

**Comment by rikardn** [comment]
Thanks and welcome! We are in the process of revising the documentation right now and I'll prioritize the contribution guidelines. I'll get back to you in this thread. Do you have any particular areas of interest or use cases that you would like to work on?

**Comment by Mutaz94** [comment]
Thanks for your response. I can be helpful in method implementation, post-processing/evaluation, and low/high level visualization. Looking forward for that :)

**Comment by rikardn** [comment]
I have added and revised the guide for new contributors: https://pharmpy.github.io/latest/contribute.html

Let us know if you already have some idea on what to work on in mind or if you want suggestions. We don't have any other todo list than the issues except the small project ideas focused on interns or summer students: https://pharmpy.github.io/latest/projects.html#projects

**Comment by Mutaz94** [comment]
That's awesome.  I went through the project lists and I have few additional ideas, first, I want to continue my revision of the current source code so I don't replicate existing functionality. One thing that I noticed with slurm jobs that PsN consumes a lot of memory with bootstrap and SIR. With Bootstrap, since its NONMEM dependent have you though of migrating to NONMEM implementation using `$SIM BOOTSTRAP=n`? I think this will be less consuming. Same thing can be done with SIR. Thanks!

**Comment by rikardn** [comment]
I have been thinking about supporting NONMEM for sir and bootstrap in the past. The benefit of having a Pharmpy implementation of the bootstrap for example is that it could be run using another estimation engine than NONMEM. The idea is that functionality in `pharmpy.tools` and `pharmpy.modeling` is agnostic to which tool is going to estimate the model. This way if we implement a separate plugin for a new estimation tool this will directly support all tools and functions. We have some rudimentary support for using nlmixr for which some models can be fit and results be picked up. I haven't tried running any more complex tools on nlmixr yet.

**Comment by rikardn** [comment]
We now have ideas to support the Bootstrap and SIR. See https://github.com/pharmpy/pharmpy/issues/2854
