### ISSUE TITLE
run_iiv: *_add_iiv model is missing in the result object

### ISSUE THREAD

**Issue by rosemarychen99** [pharmpy/pharmpy#705]
`iiv1 <- run_iiv(model = str_1, add_iivs = T, iiv_as_fullblock = T, rankfunc = "bic")`

`iiv1$models` does not have `*_add_iiv` model, even though the summary tables have it.

**Comment by stellabelin** [comment]
The `iiv1$start_model` will be the model with the added IIVs, since all candidate models are built on that model. Do you think it would be more intuitive to have it in `iiv1$models`?

**Comment by rosemarychen99** [comment]
> The `iiv1$start_model` will be the model with the added IIVs, since all candidate models are built on that model. Do you think it would be more intuitive to have it in `iiv1$models`?

The start model provided by `iiv1$start_model` is the model provided by the user, but not the model with the added IIVs.

**Comment by stellabelin** [comment]
Okay, thanks, I'll look into it!

**Comment by rosemarychen99** [comment]
It turned out the *_add_iiv.mod failed minimisation_successful. One way is to treat the *_add_iiv.mod as one candidate model?

**Comment by stellabelin** [comment]
Yes, I think that makes sense. What I'm thinking is that it might be a little bit unclear which model the dBIC is compared to

**Comment by stellabelin** [comment]
This is fixed in the new release, `start_model` has been renamed `input_model` and the model with added IIVs is called `base_model` and is available the same way as the candidate models
