### ISSUE TITLE
create_datainfo

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#709]
Add function `create_datainfo` in modeling to take a dataframe as input and output a `DataInfo`.

It should use the names of the columns to figure out reasonable `ColumnInfo` 

We should use the following as a starting point:

```
ID = id
TIME = idv
DV = dv
EVID = event
MDV = mdv
AMT = dose
```

**Comment by ZheHuang96** [comment]
Maybe I can add the default datainfo [here](https://github.com/pharmpy/pharmpy/blob/1a7a70db646ea846e43a34b81965abb83abf2338/src/pharmpy/tools/amd/funcs.py#L63)?

**Comment by rikardn** [comment]
Yes, this is the spot.

**Comment by ZheHuang96** [comment]
Ok, thank you!
