### ISSUE TITLE
calculate_bic error: "Could not find CL in Parameters"

### ISSUE THREAD

**Issue by rosemarychen99** [pharmpy/pharmpy#725]
This error happens after the recent pharmpy update.
Here is the model statement:
![image](https://user-images.githubusercontent.com/35337934/163953149-316ad67d-495d-4ba4-bc2e-accf0dcc77b2.png)

The model file will be sent in an email

**Comment by rikardn** [comment]
I don't think this is still a problem. It looks like the ODE-system wasn't even parsed correctly.
