### ISSUE TITLE
Generate extra fortran files outside the amd_dir directory

### ISSUE THREAD

**Issue by ZheHuang96** [pharmpy/pharmpy#740]
When running the amd function, we will get five extra files in the working directory, outside the correct amd_dir directory.
[AMD.zip](https://github.com/pharmpy/pharmpy/files/8552380/AMD.zip)

**Comment by ZheHuang96** [comment]
Update 05/05, it is only two extra files: **start_ccontra.f90** and **start_contr.f90**, the files which related to the start model move to the `amd_dir/modelfit7models/start`

**Comment by rikardn** [comment]
This hasen't been seen in a while so closing
