### ISSUE TITLE
Automation of R examples for web documentation

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#774]
For example tabs for Python, R and CMD-line. Possibility to execute Python code via jupyter-sphinx. Some implementation exists in pharmr and should be moved.

**Comment by pharmpy-dev-123** [comment]
We discussed this with @stellabelin and we enumerated some solutions:

  - Have one documentation build for each language, with cross-linking.
  - Write a Sphinx extension that composes `jupyter-sphinx` with one of 
    - https://github.com/executablebooks/sphinx-tabs (looks most promising)
    - https://github.com/pradyunsg/sphinx-inline-tabs
    - https://github.com/coldfix/sphinx-code-tabs

Some inspiration on how to do that: https://stackoverflow.com/questions/62980390/how-can-i-use-an-existing-directive-within-a-custom-python-sphinx-directive-exte

**Comment by rikardn** [comment]
I think writing one or multiple new Sphinx extension is the way to go. Only the Python code should be executed, but the R and cmd line code should be in separate tabs.
