### ISSUE TITLE
Changing the absorption after adding covariates is leading to a bug

### ISSUE THREAD

**Issue by SimonBuatois** [pharmpy/pharmpy#78]
Hi Rikard,

Please find enclosed the nonmem code, the dataset and the R script.

Basically when changing the absorption after adding covariates is leading to a bug:
All initial estimates for thetas are removed.
FYI, changing the absorption model and then adding covariates is working well.

Kind regards,
Simon   
[Error_afteraddingcovariates.zip](https://github.com/pharmpy/pharmpy/files/5797340/Error_afteraddingcovariates.zip)

**Comment by rikardn** [comment]
Thanks for reporting this. I can reproduce the problem.
