### ISSUE TITLE
Design Discussion: Making execute.RunDirectory Generic

### ISSUE THREAD

**Issue by billdenney** [pharmpy/pharmpy#8]
In the design document, the execute.RunDirectory class it states that it will not need to be generic (https://pharmpy.github.io/latest/design.html#rundirectory-class).  I'd like to nudge that a bit.

When used for local execution and likely for in-house clusters, I agree that the RunDirectory won't need anything generic about it-- you can work on a normal filesystem with normal filesystem operations.  I'm evaluating simplifying my in-house infrastructure by moving to AWS for computing, and with that, the RunDirectory would be more functional if it supported AWS S3 buckets.

I may be missing something about the definitions (I've not dived into the code of it), but it seems like adding the abstraction layer now would likely be easier than trying to back-fill the generic later on.

**Comment by rikardn** [comment]
This code is old and not representing the current state of development. I have been experimenting with workflow engines that would cater for AWS for example toil.

**Comment by rikardn** [comment]
When it comes to workflow engines there are so many to choose from, so I am thinking to have some generic interface so that we could switch more easily.  But all code currently in Pharmpy that does any running of models is highly experimental.

**Comment by billdenney** [comment]
Ah, great!  Given that it's outdated and this type of thing is already under consideration, I'll close this issue.

I also like the idea of a generic interface.  I'd assume that you would maintain the local execution version and likely whatever execution environment(s) are used at Uppsala, and then others would be encouraged to contribute others.  (With documentation of how to implement it.)

**Comment by rikardn** [comment]
I like your idea of having the "execution engines" as plugins. Then we could as a first implementation use Toil, but it would also leave it open for others to roll their own or add plugins for other engines like luigi or dask just to mention two others.
