### ISSUE TITLE
Suggestion: not to use the full path of the dataset in $DATA

### ISSUE THREAD

**Issue by rosemarychen99** [pharmpy/pharmpy#804]
A problem happens when the modelsearch directory is copied to another location.
I suggest to use `../.datasets/dataset_name.csv` instead.

**Comment by rikardn** [comment]
You mean in `$DATA`?  I thought we did that. If not this is a bug.

**Comment by ZheHuang96** [comment]
It seems to have the full path in the mod file but to be correct in lst file. E.g.  `/tmp/pytest-of-zhehuang/pytest-2/test_resmod0/resmod_dir1/models/.datasets/best_resmod_1.csv ` for mod file and `$DATA best_resmod_1.csv IGNORE=@` in the lst file. Not so sure it is a general problem or not.

**Comment by stellabelin** [comment]
Related to #887.

**Comment by pharmpy-dev-123** [comment]
Now tracked in #887.
