### ISSUE TITLE
Sphinx 5.0.0 blocked by sphinx-tabs

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#850]
Sphinx version 5.0.0 was recently released, but `sphinx-tabs` has the Sphinx version pinned to be <5 so we currently cannot use it. A workaround is in place to use the older Sphinx when building the documentation, but this is not ideal.

Upstream issue: https://github.com/executablebooks/sphinx-tabs/issues/162

**Comment by rikardn** [comment]
The upstream issue has been resolved and a new version has been released.

**Comment by rikardn** [comment]
Still cannot be used because of a new upstream issue: https://github.com/executablebooks/sphinx-tabs/issues/166

**Comment by pharmpy-dev-123** [comment]
> Still cannot be used because of a new upstream issue: [executablebooks/sphinx-tabs#166](https://github.com/executablebooks/sphinx-tabs/issues/166)

Seems resolved now?!

**Comment by rikardn** [comment]
Since we are at Sphinx 5.1.1 now it must be. Thanks for spotting this

**Comment by pharmpy-dev-123** [comment]
There are some references to sphinx v4 left in `tox.ini`. For instance

https://github.com/pharmpy/pharmpy/blob/8baf031e2cc8733b42fd0ef150e30eafdfc644d3/tox.ini#L76

**Comment by rikardn** [comment]
Ok, so what remains to be done here is to try to remove this workaround and see if building the documentation still works.

**Comment by rikardn** [comment]
This has been fixed
