### ISSUE TITLE
$DATA is different in .lst file vs. .ctl file

### ISSUE THREAD

**Issue by schaedeli** [pharmpy/pharmpy#887]
$DATA is different in .lst file vs. .ctl file. The .ctl has the full path and actual dataset name, .lst file includes an alias name corresponding to the candidate_model name. This is confusing and may make tracking difficult. 

Example:
modelsearch_candidate5.ctl
```
$PROBLEM ABSORPTION(SEQ-ZO-FO);PERIPHERALS(1)
$INPUT C ID AMT TIME TYPE DV EVID NDAY NTAF PROT SITE DOSE AGE SEX RACE BHT BWT BIBW BBMI BBSA BSLN BASEAH50 SADDOSE SADAH50 RATE
$DATA C:\Users\Public\ADaMO\Phase_1\Model_7\modelsearch\modelsearch_dir11\models\.datasets\modelsearch_candidate1.csv IGNORE=@
```

modelsearch_candidate5.ctl
```
Tue 05/24/2022 
05:31 PM
$PROBLEM ABSORPTION(SEQ-ZO-FO);PERIPHERALS(1)
$INPUT C ID AMT TIME TYPE DV EVID NDAY NTAF PROT SITE DOSE AGE SEX RACE BHT BWT BIBW BBMI BBSA BSLN BASEAH50 SADDOSE SADAH50 RATE
$DATA modelsearch_candidate5.csv IGNORE=@
```

This needs to be addressed. Thanks.
Franziska

**Comment by pharmpy-dev-123** [comment]
Would writing a relative path to the `.datainfo` work?

**Comment by stellabelin** [comment]
- [ ] Database method to find relative path to a model
- [ ] Recreate `.datasets` in run directory
- [ ] Double check duplication of datasets

**Comment by pharmpy-dev-123** [comment]
- [ ] Relative paths inside a `.datainfo` file should be resolved relative to that file.
  - [ ] Relative paths inside a `.mod`/`.ctl` file should be resolved relative to that file.
