### ISSUE TITLE
amd results

### ISSUE THREAD

**Issue by ZheHuang96** [pharmpy/pharmpy#904]
It would be much better if we have the final result` .json` and `.csv` file in the amd directory.
![Screenshot from 2022-06-18 12-59-08](https://user-images.githubusercontent.com/68994239/174434859-74e5769d-82f1-4b21-b1ae-cc1e3816baed.png)

**Comment by ZheHuang96** [comment]
I think it would make the results part of amd documentation easier if we can get the results.json file

**Comment by ZheHuang96** [comment]
Doing some random search in Pharmpy, I think maybe amd doesn't have a workflow so we can not get the result files as other tools? I found the `write_results` function might help us to generate JSON file?  I will have a try tomorrow but I think there must be a better way which I didn't find...

**Comment by rikardn** [comment]
Yes, these files should be created. Are they currently created in some other directory or not at all?

**Comment by ZheHuang96** [comment]
![Screenshot from 2022-06-20 16-55-52](https://user-images.githubusercontent.com/68994239/174633580-fda5c4cd-e48b-4d60-ab7e-3e99a0c5aa1e.png)
Now it works

**Comment by rikardn** [comment]
Fixed with #914
