### ISSUE TITLE
Cannot set configuration string

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#91]
Setting configuration item from string is broken, at least when calling from R.

```
> pharmpy$plugins$nonmem$conf$parameter_names <- 'comment'
> pharmpy$plugins$nonmem$conf$parameter_names
[1] "c" "o" "m" "m" "e" "n" "t"
```

The string gets split into components. It is probably because of the iterable nature of string in Python.

**Comment by stellabelin** [comment]
Setting for config is given as list, updated user guide (under Configuration) accordingly as well as added warning for using c() in R for single element list (in commit 70727917200bb9d820b927021b9f6ff6ba625dbc).
