### ISSUE TITLE
Speed up integration tests

### ISSUE THREAD

**Issue by pharmpy-dev-123** [pharmpy/pharmpy#910]
One idea would be to snapshot NONMEM's output and load it from disk instead of running NONMEM every single time.

**Comment by rikardn** [comment]
Is this really possible? I mean what is produced by NONMEM is dependent on the input it gets and the input comes from Pharmpy and might have changed.

**Comment by pharmpy-dev-123** [comment]
As long as we can serialize input and serialize/deserialize output we should be able to implement some kind of cache.

**Comment by rikardn** [comment]
We are now replacing integration tests with the dummy estimation engine, which will make them much faster and more stable. Will keep NONMEM for some tests.
