### ISSUE TITLE
Opinionated parameter naming for NONMEM models

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#919]
The current naming scheme for parameters in NONMEM models is to allow the user to set a list of priorities for how to create the parameter names. I propose that we instead fix the list of priorities and don't allow for any options. Rationale:

1. Make parameter names not dependent on the current configuration
2. Make the Pharmpy interpretation of a NONMEM model always be the same
3. Reduce the number of moving pieces in the already quite complex NONMEM model parser

I suggest that Pharmpy should always use these priorities (for population parameter names):

1. Use the parameter name given by the new NONMEM 7.5 naming
2. Use the name in the comment
3. Use the NONMEM default name

We could always have functions in modeling to convert a model to using the default NONMEM names etc

**Comment by stellabelin** [comment]
Necessary in order to use `resume_tool`, right?

**Comment by rikardn** [comment]
Yes.

If we want to keep the flexibility now or in the future we could introduce a way for the user to signal how a model file should be parsed inside the model file. For example:

```
; Pharmpy parameter_names basic,comment
```

or similar. This way it is no longer a global setting and I guess that is what we want to avoid.

**Comment by rikardn** [comment]
I propose

```
; @PHARMPY parameter_names basic,comment
```

i.e. `@PHARMPY` somewhere in a comment starts a Pharmpy specific setting where the next word is the name of the setting and then follows any arguments

**Comment by rikardn** [comment]
Just a summary of the naming discussion:

We want to achieve roundtrip names, no global state and no changes to the names when updating the code. Renumbering is currently done, but names need to stay the same when doing model building.

We should parse the names like this:

1. Use $ABBR
2. Use comments for population parameters
3. Use heuristics to give nice names, e.g. CL=THETA(1)*EXP(ETA(1)) could names THETA(1) POP_CL and ETA(1) ETA_CL and OMEGA(1,1) IIV_CL
4. Fall back to ETA_1, THETA_1 or OMEGA_1_1

When writing the model this is done to preserve the names so $ABBR or comments should be added when needed even for renumberings like ETA_1=ETA(2).

**Comment by rikardn** [comment]
This is now done (35813f76ffd993b9e917eb028a414724488688ab) and pushed. Skipped using heuristics. Using special rules for each model is also not done. Perhaps better to simply prefer comment names (or NONMEM 7.5 names in the future).
