### ISSUE TITLE
Add covariance between two IIVs

### ISSUE THREAD

**Issue by SimonBuatois** [pharmpy/pharmpy#94]
Hi,

When I tried to add two covariance (one between eta 1 and eta 2 and one between eta 2 and eta 3) I have the following error message:

![image](https://user-images.githubusercontent.com/75624013/106257521-f2f9de00-621c-11eb-963c-a0ecd07eda05.png)

The Rscript: 

############### Example (Pheno model) ##################
# Example 1
# a: Reading in a NONMEM model and printing its structure (run line by line to see the output)

model <- read_model(model_name)
print(model)

model$parameters
model$random_variables
model$statements$ode_system 

# b: Combine ETAs into a Joint normal distribution

model <- model %>%
  create_rv_block(c('ETA(1)', 'ETA(2)')) %>%
  update_source()

model$random_variables  # Graphical glitch in output is due to bug in the Rstudio text renderer
print(model)

# c: Change absorption phase first order

model <- model %>%
  first_order_absorption()%>%
  update_source()

model$parameters
model$random_variables
model$statements$ode_system
print(model)

# d: Add additional Etas
model <- model %>%
  add_iiv("MAT","exp") %>%
  update_source()

model$parameters
model$random_variables
model$statements$ode_system 
print(model)

# e: Combine ETAs into a Joint normal distribution
model <- model %>%
  create_rv_block(c('ETA(2)', 'ETA_MAT')) %>%
  update_source()

model$random_variables
print(model)

**Comment by SimonBuatois** [comment]
Hi,
Just to make sure this issue has been flagged.

Kind regards,
Simon

**Comment by stellabelin** [comment]
Hi, thanks for reporting this! I can reproduce it and get the same error. Is it that you want ETA(1), ETA(2) and ETA_MAT to be one block or to extract ETA(2) from the block in the first transformation (ETA(1) & ETA(2)) and combine ETA(2) and ETA_MAT?

**Comment by SimonBuatois** [comment]
Hi Stella,

I actually would like to have an OMEGA block like this:

ETA1, ETA2, ETA_MAT:
  0.1
  0.05 0.1
  0 0.05 0.1

One Covariance between ETA1 and ETA2 (step b), and one covariance between ETA 2 and ETA MAT (step e).

Many thanks in advance.
Simon

**Comment by stellabelin** [comment]
Okay! The easiest way right now for creating a band matrix is to create a block with all three in one step and then set the covariance between ETA1 and ETA_MAT to 0:
```
create_rv_block(model, c('ETA1', 'ETA2', 'ETA_MAT')
pset$inits['IIV_CL_IIV_MAT'] = 0  
update_source(model)
```
It is possible that a function for this is implemented in the future. However, when recreating your steps case I still get errors when I combine all three ETAs so this is a bug.

**Comment by SimonBuatois** [comment]
Thanks a lot Stella,
Given that we will build model step by step, I think that this feature should be included in the future.

Best,
Simon

**Comment by SimonBuatois** [comment]
Hi,

I managed to create a full matrix using the following commande line:
```model <- model %>%
  create_rv_block(list_of_rvs=c('ETA(1)','ETA(2)', 'ETA_MAT')) %>%
  update_source()
```

I, however, haven't managed to create a band matrix.
Could you please clarify how to perform it?

**Comment by stellabelin** [comment]
You can use `set_initial_estimates` to set the covariance to 0 manually, so this should work:

```
create_rv_block(list_of_rvs=c('ETA(1)','ETA(2)', 'ETA_MAT')) %>%
set_initial_estimates(list(IIV_CL_IIV_V=0)) %>%
update_source()
```

`IIV_CL_IIV_V` would correspond to the name of covariance parameter you're setting to 0.

**Comment by stellabelin** [comment]
Hi! Yes, we have it as an issue (#109) so the plan is to implement it!
