### ISSUE TITLE
Adding twice a combined error model is leading to a bug.

### ISSUE THREAD

**Issue by SimonBuatois** [pharmpy/pharmpy#95]
Hi,

As a test, I tried to twice add the same error model (combined error).
When doing so a bug is occurring:
-Instead of leaving the code as is, it is adding RUV on the error model.
(FYI, in addition, no Theta is associated to the RUV).

![image](https://user-images.githubusercontent.com/75624013/106261240-9b11a600-6221-11eb-8d78-540f8163278b.png)

# Example (Pheno)
## a: Reading in a NONMEM model and printing its structure (run line by line to see the output)

model <- read_model(model_name)
print(model)

model$parameters
model$random_variables
model$statements$ode_system 

## b: combined additive and proportional error model
model <- model %>%
  combined_error() %>%
  update_source()

model$parameters
model$random_variables
model$statements$ode_system 
print(model)

## bbis: combined additive and proportional error model
model <- model %>%
  combined_error() %>%
  update_source()

model$parameters
model$random_variables
model$statements$ode_system 
print(model)

**Comment by rikardn** [comment]
Thanks for testing this! There might be other transformations that doesn't work if applied twice. This is a bug

**Comment by SimonBuatois** [comment]
Yes indeed, 
the same thing happen when adding twice an additive or proportional error model alone.
