### ISSUE TITLE
Add level in log for critical errors 

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#964]
Such as the one mentioned in this issue: https://github.com/pharmpy/pharmr/issues/71. Should .ext-file still be read in case of critical errors?

**Comment by joaoabr** [comment]
if the *.ext file is not read (e.g. if min successful/terminated message does not appear), the OFV and BIC could appear as NA in table of results and the respective models also with ranking NA

**Comment by stellabelin** [comment]
I've created a separate issue where `summary_tool` do not include OFV/BIC etc. if the minimization was terminated which you can find here: #1056. A critical log level is not necessary for this currently.

**Comment by rikardn** [comment]
We now have a critical level in the log of the `Context`. This is reserved for errors where the tool needs to terminate itself.
