### ISSUE TITLE
Fix issue with fortran compiler on GHA

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#968]
When running integration tests, the test of gfortran in NONMEM fails on Windows:

```
===Checking compiler
start compile/link
end compile/link
Cannot run a.out
===
Compiler gfortran and/or install program cannot be run
Installation Aborted
```

This change seem to be due to a new image of the virtual machine (20220626.1, before it was 20220614.0). As a temporary workaround, we use windows-2019 instead of windows-2022. Things to look into could be NONMEM 7.5 (don't know if this will solve it) or to find the source of this error.

**Comment by pharmpy-dev-123** [comment]
It seems we have the same problem with NONMEM 7.5: https://github.com/pharmpy-dev-123/gha-nonmem/actions

**Comment by stellabelin** [comment]
We now use windows-2022 and NONMEM 7.5, closing this issue.
