### ISSUE TITLE
Apply zero-protect by default

### ISSUE THREAD

**Issue by cossonvalerie** [pharmpy/pharmpy#969]
Hi, 
The initial_model (created through combination of assemblerr model and pharmr function) did not start for the first dataset tested (IV route).  We experienced the same problem with a second dataset for IV route again
When applying the zero_protect function, the initial_model run well.  We still need to test the zero_protect function with the second dataset and see if it solves the issue as for the first dataset.

Our suggestion would be to applying by defaut the zero_protect function for PROP RUV whatever the route and not only for oral route as it currently done.

**Comment by rikardn** [comment]
For the generated start model in the amd tool we always add the zero protection. Is this still a problem for any of the subtools?

**Comment by emiliesg** [comment]
Hi, would it be possible to set the default for zero_protection in set_proportional_error_model to True instead of False to have it included by default.

**Comment by ZheHuang96** [comment]
Hi @emiliesg , thank you for your suggestion! It is possible and we will set `zero_protection = True ` as default in `set_proportional_error_model()`.
