### ISSUE TITLE
Ctl from iivsearch: the first iiv labels within $ OMEGA are not populated

### ISSUE THREAD

**Issue by cossonvalerie** [pharmpy/pharmpy#974]
Issue with iivsearch (before latest update of PharmPy). I used the following arguments: algorithm= problem brute_force, iiv_strategy=2
In the created ctl files, the first iiv labels within $ OMEGA are not populated. See example below:

$PROBLEM [QP1,VC,CL,VP2,VP1]
$INPUT C ID PT STUD TIME NOMTIME TAD NOMTAD AMT RATE DV EVID BLQ NOMDOSE AGE SEX RACE WT BMI BSA COHORT PART FLAG COMMENT
$DATA C:\Users\Public\ADaMO\Phase_1\Model_1\modelsearch_RUV\iivsearch_dir1\models\.datasets\iivsearch_no_of_etas_candidate3.csv IGNORE=@
$SUBROUTINES ADVAN11  TRANS4 
$PK
VP2 = THETA(6)*EXP(ETA(3))
QP2 = THETA(5)
VP1 = THETA(4)*EXP(ETA(5))
QP1 = THETA(3)*EXP(ETA(4))
VC = THETA(1) * EXP(ETA(1))
CL = THETA(2) * EXP(ETA(2))
(…)
$OMEGA BLOCK(5)
0.0327614
0.00138284
0.0735302
0.0241255	; IIV_VC_IIV_VP2
0.0184285	; IIV_CL_IIV_VP2
0.0347973	; IIV_VP2
-0.089532	; IIV_VC_IIV_QP1
0.1722	; IIV_CL_IIV_QP1
0.00241256	; IIV_VP2_IIV_QP1
1.05783	; IIV_QP1
-0.0222261	; IIV_VC_IIV_VP1
0.0726135	; IIV_CL_IIV_VP1
0.0143251	; IIV_VP2_IIV_VP1
0.489515	; IIV_QP1_IIV_VP1
0.286161	; IIV_VP1
$SIGMA  0.00676925 ; sigma

**Comment by stellabelin** [comment]
Hi! Thank you! This might be related to this bug: #790
