### ISSUE TITLE
Incorrect example code

### ISSUE THREAD

**Issue by ZheHuang96** [pharmpy/pharmpy#979]
For some reason, `from pharmpy.modeling import *` didn't work so I have to use `from pharmpy.tools import fit`.
 https://pharmpy.github.io/latest/api/pharmpy.tools.fit.html?highlight=fit#pharmpy.tools.fit

Not so sure if it is a general issue or not. My system is Windows and I use spyder.

**Comment by pharmpy-dev-123** [comment]
`fit` has moved to `pharmpy.tools`. All examples that try to import it from `pharmpy.modeling` should be changed.

**Comment by ZheHuang96** [comment]
I can change the example for `fit`

**Comment by pharmpy-dev-123** [comment]
> Yes, I think so too. I am curious about the reason that the example can pass all the checks? I thought our documentation test would check the examples and maybe I am wrong....

This example probably skips the line fitting the model since that would involve NONMEM.

**Comment by ZheHuang96** [comment]
Ah, I see. Thank you for your help:)
