### ISSUE TITLE
Name of non-diagonal elements of omega matrix

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmpy#98]
When adding full/partial omega block structures, the new elements were called COVN.
```
model <- model %>%
    create_rv_block(c('ETA(1)', 'ETA(2)', 'ETA(3)')) %>%
    update_source()

 $OMEGA BLOCK(3)
 0.0703478 ; IIV_CL
 0.0070348 ; COV1
 0.0703478 ; IIV_V
 0.0070348 ; COV2
 0.0070348 ; COV3
 0.0703478 ; IIV_MAT
```
Would it be possible to give a more informative name to the newly created elements (eg. IIV_CL_V1 instead  #of COV1)?

**Comment by rikardn** [comment]
Thanks for the suggestion. I agree that we should generate better names for the covariances. We need to figure out a general way to do this. Two ideas:

1. Check what individual parameters the ETAs are acting on
2. Use the names of the variance OMEGAs.

Both suggestions have drawbacks. For the first case the ETA might be acting on multiple individual parameters. For the second we need some name mangling heuristics. What do we do if the OMEGAs are named `CL` and `V` and when they are named `IIV_CL` and `IIV_V`?

I suggest that we use option 1 and in the case of multiple parameters select the one where the ETA last appeared in the code. This should mostly be an unusual case I think.

**Comment by SimonBuatois** [comment]
Hi,

I agree with your suggestion. Option 1 seems to be the best solution. 
I'm however not sure to understand the following sentence:" in the case of multiple parameters select the one where the ETA last appeared in the code". Can you clarify?

Kind regards,
Simon

**Comment by joaoabr** [comment]
Hi Rikard,

After discussing it with other testers, we concluded that Option 1 is indeed a good solution. We also thought that the name could come from the combination of parameter 1 + parameter 2. For instance, if omega 1 is called `IIV_CL` and omega 2 is called `IIV_V`, the covariance element could be called `COV_IIV_CL_IIV_V` (or `COV_CL_V`), or something on this line. 

In the rare case that an omega 1 would affect `KA` and `V`, this could be called `IIV_KA_V`, and the covariance with `CL` would be `COV_IIV_KA_V_IIV_CL`. 

What are your thoughts?

**Comment by stellabelin** [comment]
Hi! The current solution is to display it as `IIV_CL_V` (e3a98b8b54f85534729282185f5fd0ee69f5230e), would it be more accurate/would you prefer `IIV_CL_IIV_V`? This will be included in the next release. I suggest the second point on what to do when an ETA is acting on multiple parameters can be decided once Rikard is back, for now Rikard's solution of only using the last one is implemented, but using all parameter names would be very fast to change to.
