### ISSUE TITLE
Fail loudly when or handle passing strings instead of lists as continuous/categorical to `run_amd`

### ISSUE THREAD

**Issue by pharmpy-dev-123** [pharmpy/pharmpy#983]
@liuxl17 reported this.

**Comment by liuxl17** [comment]
The error still exists when using lists as continuous/categorical to ```run_amd```. This error happens at the covsearch step because the covsearch folder is created in the amd_dir_# folder but is empty. 
![image](https://user-images.githubusercontent.com/53524647/179853127-28346b5c-9653-4ee7-9578-9cdf9a086fad.png)

**Comment by pharmpy-dev-123** [comment]
Can you include the code snippet that produces this error?

**Comment by liuxl17** [comment]
> Can you include the code snippet that produces this error?

Here is the code I used:
```
dataset_path <- "Data/dauno_clean.csv"

mfl <- "PERIPHERALS([1,2])"
order <- c('structural', 'iivsearch', 'residual', 'allometry', 'covariates')
res <- run_amd(input=dataset_path,
               modeltype='pk_iv',
               search_space=mfl,
               order=order,
               categorical=c('SEX'),
               continuous=c('AGE'),
               allometric_variable='WT')
```

**Comment by pharmpy-dev-123** [comment]
Thanks! What is your Pharmpy version?

**Comment by pharmpy-dev-123** [comment]
Oh! This error has already come up somewhere else (https://github.com/pharmpy/pharmr/issues/89), can you try `list('...')` instead of `c('...')` for the categorical and continuous keyword arguments?

**Comment by liuxl17** [comment]
> Thanks! What is your Pharmpy version?

0.73.1


> Oh! This error has already come up somewhere else ([pharmpy/pharmr#86](https://github.com/pharmpy/pharmr/issues/86)), can you try `list('...')` instead of `c('...')` for the categorical and continuous keyword arguments?

Yeah it works! Thank you!

**Comment by pharmpy-dev-123** [comment]
See another instance of consequences of absence of input checks:
  - https://github.com/pharmpy/pharmr/issues/100#issuecomment-1206471567

**Comment by stellabelin** [comment]
I've created an issue for input checking here: #1032. Can I close this issue?

**Comment by pharmpy-dev-123** [comment]
Yes, please close.
