### ISSUE TITLE
Fail to run covsearch if not specify continuous/categorical variables

### ISSUE THREAD

**Issue by liuxl17** [pharmpy/pharmpy#986]
Here is the code and error infomation:
```
mfl <- "PERIPHERALS([1,2])"
res <- run_amd(input=dataset_path, 
               modeltype='pk_iv', 
               order=NULL, 
               search_space=mfl,
               occasion='MOCC')
```
![image](https://user-images.githubusercontent.com/53524647/180028153-df9402ee-630b-41d2-8150-6624dc2f4f84.png)

The running stops at covsearch step. The covsearch folder is created but empty. But it runs smoothly if the continuous/categorical variables are specified correctly like below:
```
mfl <- "PERIPHERALS([1,2])"
res <- run_amd(input=dataset_path, 
               modeltype='pk_iv', 
               order=NULL, 
               search_space=mfl,
               categorical=list('SEX'),
               continuous=list('AGE'),
               allometric_variable='WT',
               occasion='MOCC')
```

**Comment by ZheHuang96** [comment]
Do you specify the covariates in your datainfo? @liuxl17

**Comment by liuxl17** [comment]
> Do you specify the covariates in your datainfo? @liuxl17

Ah yeah, that's the problem. I added covariate label to the datainfo file and now it works well. Thank you.

**Comment by pharmpy-dev-123** [comment]
Currently the default is to pull the covariates from the datainfo. If they are not defined there then it produces an empty search space. An empty search space makes postprocessing results production error. Maybe we should handle this particular error more gracefully, and perhaps have an appropriate warning. But you definitely need to define the covariates either in the datainfo or via `run_amd` keyword arguments. There is currently no automatic discovery of such covariates.
